function parameters = deriveCartesianAdmittanceParameters(cfg)
%DERIVECARTESIANADMITTANCEPARAMETERS Derive diagonal M/D from user values.

validateCartesianAdmittanceDragConfig(cfg);
t = cfg.cartesianDrag.Translation;
r = cfg.cartesianDrag.Rotation;
translationDamping = t.DesignForceN / t.TargetSteadySpeedMSec;
rotationDamping = r.DesignMomentNm / r.TargetSteadySpeedRadSec;
parameters = struct();
parameters.Damping = [translationDamping * ones(3, 1); ...
    rotationDamping * ones(3, 1)];
parameters.VirtualMass = [ ...
    translationDamping * t.TimeConstantSec * ones(3, 1); ...
    rotationDamping * r.TimeConstantSec * ones(3, 1)];
parameters.DesignEffort = [t.DesignForceN * ones(3, 1); ...
    r.DesignMomentNm * ones(3, 1)];
parameters.TargetSteadyVelocity = [ ...
    t.TargetSteadySpeedMSec * ones(3, 1); ...
    r.TargetSteadySpeedRadSec * ones(3, 1)];
parameters.TimeConstantSec = [t.TimeConstantSec * ones(3, 1); ...
    r.TimeConstantSec * ones(3, 1)];
parameters.MaximumVelocity = [t.MaximumSpeedMSec * ones(3, 1); ...
    r.MaximumSpeedRadSec * ones(3, 1)];
parameters.MaximumAcceleration = [ ...
    t.MaximumAccelerationMSec2 * ones(3, 1); ...
    r.MaximumAccelerationRadSec2 * ones(3, 1)];
parameters.RelativeLimit = [double(t.RelativeLimitM(:)); ...
    double(r.RelativeLimitRad(:))];
parameters.TravelLimitsEnabled = ...
    logical(cfg.cartesianDrag.TravelLimitsEnabled);
parameters.VelocityZeroTolerance = ...
    double(cfg.cartesianDrag.VelocityZeroTolerance(:));
end
