function schedule = stage07FaultSchedule()
%STAGE07FAULTSCHEDULE Single source of truth for Stage 7 fault timing.

schedule = struct();
schedule.TimeSec = [15; 30; 45; 60; 75];
schedule.DurationSec = 0.12 * ones(5, 1);
schedule.FieldName = [ ...
    "HandleStale"; ...
    "ForceStale"; ...
    "RobotStale"; ...
    "QpFailure"; ...
    "ControlOverrun"];
schedule.StatusCode = [ ...
    "INJECT_HANDLE_STALE"; ...
    "INJECT_FORCE_STALE"; ...
    "INJECT_ROBOT_STALE"; ...
    "INJECT_QP_FAILURE"; ...
    "INJECT_CONTROL_OVERRUN"];
schedule.ShortLabel = [ ...
    "HANDLE_STALE"; ...
    "FORCE_STALE"; ...
    "ROBOT_STALE"; ...
    "QP_FAILURE"; ...
    "CONTROL_OVERRUN"];
schedule.NameZh = [ ...
    "软件使能输入过期"; ...
    "力信号过期"; ...
    "机器人反馈过期"; ...
    "QP 求解失败"; ...
    "控制周期超时"];
end
