function [review, outputDirectory] = run_stage04_final_review(options)
%RUN_STAGE04_FINAL_REVIEW Run and archive the Stage 4 offline exit audit.
% This function runs tests and inspects configuration only. It creates no
% robot/sensor adapter and sends no hardware command.

arguments
    options.WriteResults (1, 1) logical = true
end

projectRoot = string(fileparts(mfilename('fullpath')));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'config'));
cfg = defaultRcmAdmittanceConfig();
testResults = runAllTests();
testNames = string({testResults.Name}).';
testPassed = [testResults.Passed].';
testFailed = [testResults.Failed].';
testIncomplete = [testResults.Incomplete].';
testDurationSec = [testResults.Duration].';
stage04Mask = contains(testNames, ...
    "testStage04DeadmanAndIntegrator/");

allTestsPassed = ~isempty(testResults) && all(testPassed);
stage04TestsPassed = sum(stage04Mask) >= 10 && ...
    all(testPassed(stage04Mask));
debounceInPlannedRange = cfg.handle.RisingDebounceSec >= 0.030 && ...
    cfg.handle.RisingDebounceSec <= 0.050;
staleWithinTwoNominalCycles = cfg.handle.StaleSec <= ...
    2 * cfg.runtime.NominalDtSec + 10 * eps;
softStartInPlannedRange = cfg.handle.SoftStartSec >= 0.100 && ...
    cfg.handle.SoftStartSec <= 0.300;
softwareInputCannotAuthorizeMotion = ...
    ~cfg.handle.SoftwareInputSupportsPhysicalMotion;
keyboardRepeatFilterBounded = ...
    cfg.handle.KeyboardReleaseConfirmSec > 0 && ...
    cfg.handle.KeyboardReleaseConfirmSec <= 0.050;
authorization = scopeguide.safety.evaluateMotionAuthorization(cfg, "");
defaultMotionDenied = ~authorization.Allowed;

checks = [ ...
    makeCheck("full_offline_regression", allTestsPassed, ...
        sprintf('%d/%d passed; failed=%d; incomplete=%d', ...
        sum(testPassed), numel(testResults), sum(testFailed), ...
        sum(testIncomplete))); ...
    makeCheck("stage04_timeline_tests", stage04TestsPassed, ...
        sprintf('%d Stage 4 tests passed', sum(stage04Mask))); ...
    makeCheck("rising_edge_debounce", debounceInPlannedRange, ...
        sprintf('configured %.0f ms', ...
        1e3 * cfg.handle.RisingDebounceSec)); ...
    makeCheck("handle_stale_watchdog", staleWithinTwoNominalCycles, ...
        sprintf('stale %.0f ms; two nominal cycles %.0f ms', ...
        1e3 * cfg.handle.StaleSec, ...
        2e3 * cfg.runtime.NominalDtSec)); ...
    makeCheck("enable_soft_start", softStartInPlannedRange, ...
        sprintf('configured %.0f ms', ...
        1e3 * cfg.handle.SoftStartSec)); ...
    makeCheck("software_input_not_physical_deadman", ...
        softwareInputCannotAuthorizeMotion, ...
        'SupportsPhysicalMotion=false'); ...
    makeCheck("keyboard_auto_repeat_filter", ...
        keyboardRepeatFilterBounded, ...
        sprintf('release confirmation %.0f ms; dry-run only', ...
        1e3 * cfg.handle.KeyboardReleaseConfirmSec)); ...
    makeCheck("default_physical_motion_denied", defaultMotionDenied, ...
        sprintf('%d safety gates remain closed', ...
        numel(authorization.FailedGates))); ...
    makeCheck("implementation_files_present", ...
        implementationFilesPresent(projectRoot), ...
        'adapter, FSM, integrator and keyboard/mouse demo found')];

review = struct();
review.Stage = 4;
review.ReviewedAtLocal = string(datetime('now', ...
    'TimeZone', 'Asia/Shanghai', ...
    'Format', 'yyyy-MM-dd HH:mm:ss Z'));
review.Status = "not_passed";
review.AllExitChecksPassed = all([checks.Passed]);
if review.AllExitChecksPassed
    review.Status = "passed";
end
review.OfflineOnly = true;
review.HardwareConnectionsCreated = false;
review.MotionCommandsSent = false;
review.FullTestCount = numel(testResults);
review.FullTestPassed = sum(testPassed);
review.FullTestFailed = sum(testFailed);
review.FullTestIncomplete = sum(testIncomplete);
review.Stage04TestCount = sum(stage04Mask);
review.Stage04TestPassed = sum(testPassed(stage04Mask));
review.Checks = checks;
review.States = ["DISABLED", "PREARM", "ENABLED", ...
    "STOPPING", "FAULT"];
review.SoftwareInputSources = ["keyboard_space_hold", ...
    "mouse_pad_hold"];
review.SoftwareInputSupportsPhysicalMotion = false;
review.ReleaseCommandZeroDeadlineCycles = 1;
review.FaultResetPolicy = ...
    "latched_until_explicit_reset_after_release_and_recovery";
review.IntegratorPolicy = ...
    "measured_dt_reanchor_on_stop_fault_or_long_period";
review.NextStage = 5;
review.NextStageDependencyNote = ...
    "Stage 5 offline work also needs the supplied manual pRcmBase";

if options.WriteResults
    timestamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss_SSS'));
    outputDirectory = fullfile(projectRoot, 'results', ...
        "stage04_final_review_" + timestamp);
    [created, message] = mkdir(outputDirectory);
    if ~created && ~isfolder(outputDirectory)
        error('scopeguide:stage04:CannotCreateReviewDirectory', ...
            'Cannot create %s: %s', outputDirectory, message);
    end
    writeJson(fullfile(outputDirectory, 'summary.json'), review);
    writeJson(fullfile(outputDirectory, 'config_snapshot.json'), cfg);
    writetable(struct2table(checks), ...
        fullfile(outputDirectory, 'checks.csv'));
    testTable = table(testNames, testPassed, testFailed, ...
        testIncomplete, testDurationSec, ...
        'VariableNames', {'Name', 'Passed', 'Failed', ...
        'Incomplete', 'DurationSec'});
    writetable(testTable, fullfile(outputDirectory, 'test_results.csv'));
    writeMarkdown(fullfile(outputDirectory, 'report.md'), review, cfg);
else
    outputDirectory = "";
end

fprintf('Stage 4 final review: %s\n', upper(review.Status));
fprintf('Offline tests: %d / %d passed.\n', ...
    review.FullTestPassed, review.FullTestCount);
fprintf('Hardware connections: 0; motion commands: 0.\n');
if strlength(outputDirectory) > 0
    fprintf('Results: %s\n', outputDirectory);
end
end

function present = implementationFilesPresent(projectRoot)
files = [ ...
    fullfile(projectRoot, '+scopeguide', '+io', ...
        'EnableHandleAdapter.m'); ...
    fullfile(projectRoot, '+scopeguide', '+control', ...
        'HandleEnableStateMachine.m'); ...
    fullfile(projectRoot, '+scopeguide', '+control', ...
        'JointCommandIntegrator.m'); ...
    fullfile(projectRoot, 'run_stage04_software_deadman_demo.m')];
present = all(arrayfun(@isfile, files));
end

function item = makeCheck(name, passed, evidence)
item = struct('Name', string(name), 'Passed', logical(passed), ...
    'Evidence', string(evidence));
end

function writeJson(filePath, value)
try
    encoded = jsonencode(value, 'PrettyPrint', true);
catch
    encoded = jsonencode(value);
end
[fileId, message] = fopen(filePath, 'w');
if fileId < 0
    error('scopeguide:stage04:CannotWriteReview', ...
        'Cannot open %s: %s', filePath, message);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', encoded);
clear cleanup;
end

function writeMarkdown(filePath, review, cfg)
[fileId, message] = fopen(filePath, 'w');
if fileId < 0
    error('scopeguide:stage04:CannotWriteReview', ...
        'Cannot open %s: %s', filePath, message);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '# Stage 4 final review\n\n');
fprintf(fileId, '- Status: **%s**\n', upper(review.Status));
fprintf(fileId, '- Reviewed: %s\n', review.ReviewedAtLocal);
fprintf(fileId, '- Tests: %d/%d passed\n', ...
    review.FullTestPassed, review.FullTestCount);
fprintf(fileId, ...
    '- Offline only; hardware connections: 0; motion commands: 0\n\n');
fprintf(fileId, '## Exit checks\n\n');
fprintf(fileId, '| Check | Passed | Evidence |\n');
fprintf(fileId, '|---|:---:|---|\n');
for index = 1:numel(review.Checks)
    item = review.Checks(index);
    if item.Passed
        mark = 'yes';
    else
        mark = 'no';
    end
    fprintf(fileId, '| %s | %s | %s |\n', ...
        item.Name, mark, item.Evidence);
end
fprintf(fileId, '\n## Frozen behavior\n\n');
fprintf(fileId, '- Rising debounce: %.0f ms.\n', ...
    1e3 * cfg.handle.RisingDebounceSec);
fprintf(fileId, '- Input stale timeout: %.0f ms.\n', ...
    1e3 * cfg.handle.StaleSec);
fprintf(fileId, '- Soft start: %.0f ms.\n', ...
    1e3 * cfg.handle.SoftStartSec);
fprintf(fileId, '- Keyboard release confirmation: %.0f ms, dry-run only.\n', ...
    1e3 * cfg.handle.KeyboardReleaseConfirmSec);
fprintf(fileId, ...
    '- Release zeros command and reanchors within one control cycle.\n');
fprintf(fileId, ...
    '- Faults latch until release, recovery and explicit reset.\n');
fprintf(fileId, ...
    ['- Keyboard/mouse inputs are dry-run only and cannot authorize ' ...
    'physical motion.\n\n']);
fprintf(fileId, ...
    'Next: Stage 5 force-only 3-DOF admittance after pRcmBase is supplied.\n');
clear cleanup;
end
