function [review, outputDirectory] = run_stage02_final_review(options)
%RUN_STAGE02_FINAL_REVIEW Audit the Stage 2 exit evidence offline.
% This function only reads saved reports and runs offline tests.  It never
% constructs a robot adapter, opens a robot connection or sends a command.

arguments
    options.LiveAggregateDirectory (1, 1) string = ""
    options.CurrentAssemblyReportDirectory (1, 1) string = ""
    options.RunTests (1, 1) logical = true
    options.WriteResults (1, 1) logical = true
end

projectRoot = string(fileparts(mfilename('fullpath')));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'config'));

liveDirectory = resolveEvidenceDirectory( ...
    options.LiveAggregateDirectory, projectRoot, ...
    "stage02_live_readonly_aggregate_*");
assemblyDirectory = resolveEvidenceDirectory( ...
    options.CurrentAssemblyReportDirectory, projectRoot, ...
    "stage02_recorded_kinematics_*");
live = readJson(fullfile(liveDirectory, 'summary.json'));
assembly = readJson(fullfile(assemblyDirectory, 'summary.json'));
poseDirectories = string(live.ResultDirectories(:));
poseSummaries = cell(numel(poseDirectories), 1);
for index = 1:numel(poseDirectories)
    poseSummaries{index} = readJson(fullfile( ...
        poseDirectories(index), 'summary.json'));
end

cfg = defaultRcmAdmittanceConfig();
if options.RunTests
    testResults = runAllTests();
    testTotal = numel(testResults);
    testPassed = sum([testResults.Passed]);
    testFailed = sum([testResults.Failed]);
    testIncomplete = sum([testResults.Incomplete]);
    testsPassed = testTotal > 0 && testPassed == testTotal;
else
    testTotal = 0;
    testPassed = 0;
    testFailed = 0;
    testIncomplete = 0;
    testsPassed = false;
end

poseCount = double(live.PoseRunCount);
poseSeparationRad = double(live.MinimumMeanJointPoseSeparationRad);
distinctPoses = poseCount >= 3 && logical(live.AllPoseLabelsUnique) && ...
    isfinite(poseSeparationRad) && poseSeparationRad >= 0.25;
noCommands = logical(live.AllPhysicalMotionCommandSentFalse) && ...
    double(live.TotalAdapterCommandSentCount) == 0;

feedbackHealthy = true;
for index = 1:numel(poseSummaries)
    item = poseSummaries{index};
    feedbackHealthy = feedbackHealthy && ...
        double(item.ValidReadRatio) == 1 && ...
        double(item.StaleReadRatio) == 0 && ...
        double(item.InvalidFeedbackByteCountIncrease) == 0 && ...
        double(item.FeedbackSequenceRegressionCount) == 0 && ...
        logical(item.TimingDataSufficient);
end
staleThresholdSupported = cfg.robot.FeedbackStaleSec >= ...
    double(live.SuggestedFeedbackStaleSec);

liveReference = string(live.InferredControllerPoseReference);
assemblyReference = string( ...
    assembly.InferredHistoricalControllerPoseReference);
poseSemanticsVerified = liveReference == "flange" && ...
    assemblyReference == "flange";
rpyToleranceRad = 1e-4;
unitsAndOrientationVerified = ...
    cfg.robot.ControllerPoseTranslationScaleToM == 1e-3 && ...
    abs(cfg.robot.ControllerPoseAngleScaleToRad - pi / 180) < eps && ...
    double(live.RpyQuaternionMismatchMaximumRad) < rpyToleranceRad && ...
    double(assembly.RpyQuaternionMismatchMaximumRad) < rpyToleranceRad;

assemblyPoseCount = numel(double(assembly.PoseIndices));
assemblyEvidenceValid = assemblyPoseCount >= 3 && ...
    logical(assembly.AllSamplesStationary) && ...
    ~logical(assembly.PhysicalMotionCommandSent);
hardCandidateSupported = ...
    logical(live.NominalModelSupportsCurrentHardRcmCandidate) && ...
    logical(assembly.NominalModelSupportsCurrentHardRcmCandidate);
configFlagsConsistent = ...
    cfg.robot.ControllerPoseReference == "flange" && ...
    cfg.robot.ControllerPoseUnitsVerified && ...
    cfg.robot.ModelVerified && ~cfg.robot.ServoTimingVerified;

checks = [ ...
    makeCheck("offline_test_regression", testsPassed, ...
        sprintf('%d/%d tests passed; failed=%d; incomplete=%d', ...
        testPassed, testTotal, testFailed, testIncomplete)); ...
    makeCheck("three_distinct_live_poses", distinctPoses, ...
        sprintf('%d poses; minimum joint-vector separation %.6f rad', ...
        poseCount, poseSeparationRad)); ...
    makeCheck("zero_motion_commands", noCommands, ...
        sprintf('adapter sent count=%d', ...
        double(live.TotalAdapterCommandSentCount))); ...
    makeCheck("live_feedback_health", feedbackHealthy, ...
        sprintf('minimum valid ratio %.6f; P99 period %.3f ms; P99 age %.3f ms', ...
        double(live.MinimumValidReadRatio), ...
        1e3 * double(live.MaximumFeedbackPeriodP99Sec), ...
        1e3 * double(live.MaximumFeedbackAgeP99Sec))); ...
    makeCheck("feedback_stale_threshold", staleThresholdSupported, ...
        sprintf('configured %.3f ms; evidence candidate %.3f ms', ...
        1e3 * cfg.robot.FeedbackStaleSec, ...
        1e3 * double(live.SuggestedFeedbackStaleSec))); ...
    makeCheck("pose_reference_flange", poseSemanticsVerified, ...
        sprintf('live=%s; final-assembly replay=%s', ...
        liveReference, assemblyReference)); ...
    makeCheck("pose_units_and_orientation_conventions", ...
        unitsAndOrientationVerified, ...
        sprintf('live RPY/quaternion max %.3g rad; replay max %.3g rad', ...
        double(live.RpyQuaternionMismatchMaximumRad), ...
        double(assembly.RpyQuaternionMismatchMaximumRad))); ...
    makeCheck("final_assembly_multipoise_replay", ...
        assemblyEvidenceValid, ...
        sprintf('%d retained stationary poses; %d unique feedback frames', ...
        assemblyPoseCount, double(assembly.UniqueFeedbackCount))); ...
    makeCheck("nominal_model_supports_hard_candidate", ...
        hardCandidateSupported, ...
        sprintf('live max %.3f mm; replay max %.3f mm; hard candidate %.3f mm', ...
        1e3 * double(live.FlangePositionMaximumM), ...
        1e3 * double(assembly.FlangePositionMaximumM), ...
        1e3 * cfg.rcm.HardRadiusM)); ...
    makeCheck("default_config_matches_review", configFlagsConsistent, ...
        'reference=flange, units/model verified, servo timing deferred')];

review = struct();
review.Stage = 2;
review.ReviewedAtLocal = string(datetime('now', ...
    'TimeZone', 'Asia/Shanghai', ...
    'Format', 'yyyy-MM-dd HH:mm:ss Z'));
review.OfflineOnly = true;
review.HardwareConnectionsCreated = false;
review.MotionCommandsSent = false;
review.LiveAggregateDirectory = liveDirectory;
review.CurrentAssemblyReportDirectory = assemblyDirectory;
review.LivePoseDirectories = poseDirectories.';
review.TestTotal = testTotal;
review.TestPassed = testPassed;
review.TestFailed = testFailed;
review.TestIncomplete = testIncomplete;
review.Checks = checks;
review.AllExitChecksPassed = all([checks.Passed]);
if review.AllExitChecksPassed
    review.Status = "passed";
else
    review.Status = "not_passed";
end
review.ControllerPoseReferenceDecision = "flange";
review.ControllerPoseTranslationUnitDecision = "controller_mm_to_SI_m";
review.ControllerPoseAngleUnitDecision = "controller_deg_to_SI_rad";
review.QuaternionOrderDecision = "wxyz";
review.RpyConventionDecision = "Dobot_controller_RPY";
review.LiveFlangePositionMaximumM = ...
    double(live.FlangePositionMaximumM);
review.CurrentAssemblyFlangePositionMaximumM = ...
    double(assembly.FlangePositionMaximumM);
review.SoftRcmCandidateSupportedByNominalModel = ...
    review.CurrentAssemblyFlangePositionMaximumM < cfg.rcm.SoftRadiusM;
review.HardRcmCandidateSupportedByNominalModel = hardCandidateSupported;
review.ModelVerificationScope = ...
    "nominal_CR5_FK_against_controller_flange_feedback";
review.ServoTimingDecision = ...
    "deferred_until_authorized_low_speed_fixture_motion";
review.NextStage = 3;
review.NextStageEntryTask = ...
    "verify_final_tool_geometry_then_calibrate_and_repeat RCM point";

if options.WriteResults
    timestamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss_SSS'));
    outputDirectory = fullfile(projectRoot, 'results', ...
        "stage02_final_review_" + timestamp);
    [created, message] = mkdir(outputDirectory);
    if ~created && ~isfolder(outputDirectory)
        error('scopeguide:stage02:CannotCreateReviewDirectory', ...
            'Cannot create %s: %s', outputDirectory, message);
    end
    writeJson(fullfile(outputDirectory, 'summary.json'), review);
    writeJson(fullfile(outputDirectory, 'config_snapshot.json'), cfg);
    checkTable = struct2table(checks);
    writetable(checkTable, fullfile(outputDirectory, 'checks.csv'));
    writeMarkdown(fullfile(outputDirectory, 'report.md'), review, cfg);
else
    outputDirectory = "";
end

fprintf('Stage 2 final review: %s\n', upper(review.Status));
fprintf('Offline tests: %d / %d passed.\n', testPassed, testTotal);
fprintf('Live FK maximum: %.3f mm; final-assembly replay: %.3f mm.\n', ...
    1e3 * review.LiveFlangePositionMaximumM, ...
    1e3 * review.CurrentAssemblyFlangePositionMaximumM);
fprintf('Servo timing remains deferred; no robot connection was created.\n');
if strlength(outputDirectory) > 0
    fprintf('Results: %s\n', outputDirectory);
end
end

function directory = resolveEvidenceDirectory(requested, projectRoot, pattern)
if strlength(requested) > 0
    directory = requested;
else
    matches = dir(char(fullfile(projectRoot, 'results', pattern)));
    matches = matches([matches.isdir]);
    if isempty(matches)
        error('scopeguide:stage02:EvidenceDirectoryMissing', ...
            'No evidence directory matches %s.', pattern);
    end
    [~, order] = sort(string({matches.name}));
    latest = matches(order(end));
    directory = string(fullfile(latest.folder, latest.name));
end
if ~isfolder(directory)
    error('scopeguide:stage02:EvidenceDirectoryMissing', ...
        'Evidence directory does not exist: %s', directory);
end
end

function value = readJson(path)
if ~isfile(path)
    error('scopeguide:stage02:EvidenceFileMissing', ...
        'Required evidence file does not exist: %s', path);
end
value = jsondecode(fileread(path));
end

function item = makeCheck(name, passed, evidence)
item = struct('Name', string(name), 'Passed', logical(passed), ...
    'Evidence', string(evidence));
end

function writeJson(filePath, value)
try
    encoded = jsonencode(value, 'PrettyPrint', true);
catch
    encoded = jsonencode(value);
end
[fileId, message] = fopen(filePath, 'w');
if fileId < 0
    error('scopeguide:stage02:CannotWriteReview', ...
        'Cannot open %s: %s', filePath, message);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', encoded);
clear cleanup;
end

function writeMarkdown(filePath, review, cfg)
[fileId, message] = fopen(filePath, 'w');
if fileId < 0
    error('scopeguide:stage02:CannotWriteReview', ...
        'Cannot open %s: %s', filePath, message);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '# Stage 2 final review\n\n');
fprintf(fileId, '- Status: **%s**\n', upper(review.Status));
fprintf(fileId, '- Reviewed: %s\n', review.ReviewedAtLocal);
fprintf(fileId, '- Offline only: true; hardware connections: 0; commands: 0\n');
fprintf(fileId, '- Tests: %d/%d passed\n\n', ...
    review.TestPassed, review.TestTotal);
fprintf(fileId, '## Exit checks\n\n');
fprintf(fileId, '| Check | Passed | Evidence |\n');
fprintf(fileId, '|---|:---:|---|\n');
for index = 1:numel(review.Checks)
    item = review.Checks(index);
    if item.Passed
        mark = 'yes';
    else
        mark = 'no';
    end
    fprintf(fileId, '| %s | %s | %s |\n', ...
        item.Name, mark, item.Evidence);
end
fprintf(fileId, '\n## Boundary decision\n\n');
fprintf(fileId, ...
    '- Live three-pose maximum flange error: %.3f mm.\n', ...
    1e3 * review.LiveFlangePositionMaximumM);
fprintf(fileId, ...
    '- Final-assembly 12-pose maximum flange error: %.3f mm.\n', ...
    1e3 * review.CurrentAssemblyFlangePositionMaximumM);
fprintf(fileId, ...
    '- The nominal model does not support the %.1f mm soft candidate.\n', ...
    1e3 * cfg.rcm.SoftRadiusM);
fprintf(fileId, ...
    ['- The nominal model supports proceeding with the %.1f mm hard ' ...
    'candidate for later validation; this is not physical RCM validation.\n'], ...
    1e3 * cfg.rcm.HardRadiusM);
fprintf(fileId, ...
    ['- Servo command timing remains unverified until authorized ' ...
    'low-speed fixture motion.\n\n']);
fprintf(fileId, '## Evidence\n\n');
fprintf(fileId, '- Live aggregate: `%s`\n', ...
    review.LiveAggregateDirectory);
fprintf(fileId, '- Final-assembly replay: `%s`\n\n', ...
    review.CurrentAssemblyReportDirectory);
fprintf(fileId, 'Next: Stage 3 tool-geometry review and repeated RCM calibration.\n');
clear cleanup;
end
