function [review, outputDirectory] = run_stage06_final_review(options)
%RUN_STAGE06_FINAL_REVIEW Run and archive the offline Stage 6 exit audit.
% No robot/sensor adapter is constructed and no hardware command is sent.

arguments
    options.WriteResults (1, 1) logical = true
    options.WorkspaceSampleCount (1, 1) double = 300
end

projectRoot = string(fileparts(mfilename('fullpath')));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'config'));
cfg = defaultRcmAdmittanceConfig();
testResults = runAllTests();
testNames = string({testResults.Name}).';
testPassed = [testResults.Passed].';
testFailed = [testResults.Failed].';
testIncomplete = [testResults.Incomplete].';
testDurationSec = [testResults.Duration].';
stage06Mask = contains(testNames, "testStage06RcmConstrainedQp/");

[workspaceScan, ~] = run_stage06_qp_workspace_scan( ...
    SampleCount=options.WorkspaceSampleCount, RandomSeed=606, ...
    WriteResults=false);
scanSummary = workspaceScan.Summary;
authorization = scopeguide.safety.evaluateMotionAuthorization(cfg, "");
quadprogAvailable = exist('quadprog', 'file') == 2 && ...
    logical(license('test', 'Optimization_Toolbox'));

checks = [ ...
    makeCheck("quadprog_route_verified", quadprogAvailable, ...
        char(string(which('quadprog')))); ...
    makeCheck("full_offline_regression", ...
        ~isempty(testResults) && all(testPassed), ...
        sprintf('%d/%d passed; failed=%d; incomplete=%d', ...
        sum(testPassed), numel(testResults), sum(testFailed), ...
        sum(testIncomplete))); ...
    makeCheck("stage06_automatic_tests", ...
        sum(stage06Mask) >= 11 && all(testPassed(stage06Mask)), ...
        sprintf('%d Stage 6 tests passed', sum(stage06Mask))); ...
    makeCheck("rcm_jacobian_and_three_modes", ...
        namedTestsPassed(testNames, testPassed, stage06Mask, ...
        ["RcmJacobianMatches", "HardSoftAndHybrid"]), ...
        'finite difference plus hard/soft/hybrid solve tests passed'); ...
    makeCheck("joint_and_prediction_constraints", ...
        namedTestsPassed(testNames, testPassed, stage06Mask, ...
        ["JointSpeedAcceleration", "HybridHardEnvelope"]), ...
        'speed, acceleration, one-step position, RCM and travel bounds passed'); ...
    makeCheck("failure_paths_zero_output", ...
        namedTestsPassed(testNames, testPassed, stage06Mask, ...
        ["InfeasibleBounds", "TimeoutAndAbnormalExit", ...
        "ConsecutiveFailures"]), ...
        'infeasible/timeout/exit-flag paths return zero and escalate deterministically'); ...
    makeCheck("singularity_gradual_scale_and_stop", ...
        namedTestsPassed(testNames, testPassed, stage06Mask, ...
        "SingularityScaleShrinksAndStops"), ...
        'scaled Jacobian sigma produces global shrink and exact-zero stop'); ...
    makeCheck("workspace_feasibility_scan", ...
        scanSummary.WorkspaceScanPassed, ...
        sprintf('%d/%d solved (%.2f%%); singular stops=%d; unexpected=%d', ...
        scanSummary.SolvedCount, scanSummary.SampleCount, ...
        100 * scanSummary.FeasibilityRate, ...
        scanSummary.SingularStopCount, ...
        scanSummary.UnexpectedFailureCount)); ...
    makeCheck("qp_timing_budget", scanSummary.TimingBudgetPassed, ...
        sprintf('P50/P95/P99 %.3f/%.3f/%.3f ms; budget %.3f ms', ...
        1e3 * scanSummary.OverallTiming.P50Sec, ...
        1e3 * scanSummary.OverallTiming.P95Sec, ...
        1e3 * scanSummary.OverallTiming.P99Sec, ...
        1e3 * scanSummary.QpSolveBudgetSec)); ...
    makeCheck("constraint_residual", ...
        scanSummary.AllSuccessfulConstraintsWithinTolerance, ...
        sprintf('maximum violation %.3g; tolerance %.3g', ...
        scanSummary.MaximumConstraintViolation, ...
        cfg.qp.ConstraintTolerance)); ...
    makeCheck("physical_motion_still_denied", ~authorization.Allowed && ...
        ~cfg.rcm.CalibrationValid && ~cfg.rcm.BoundsValidated, ...
        sprintf('%d motion gates closed; real RCM remains unvalidated', ...
        numel(authorization.FailedGates)))];

review = struct();
review.Stage = 6;
review.ReviewedAtLocal = string(datetime('now', ...
    'TimeZone', 'Asia/Shanghai', ...
    'Format', 'yyyy-MM-dd HH:mm:ss Z'));
review.Status = "not_passed";
review.AllExitChecksPassed = all([checks.Passed]);
if review.AllExitChecksPassed
    review.Status = "passed_offline";
end
review.Scope = "hard/soft/hybrid RCM-constrained quadprog offline validation";
review.Solver = "quadprog";
review.NoFallbackSolverUsed = true;
review.SelectedControlRateHz = cfg.runtime.ControlRateHz;
review.QpSolveBudgetSec = cfg.qp.MaximumSolveTimeSec;
review.WarmupRequiredBeforePrearm = true;
review.OfflineOnly = true;
review.GeometryUsedForReview = scanSummary.GeometrySource;
review.RealRcmCalibrationClaimed = false;
review.HardwareConnectionsCreated = false;
review.MotionCommandsSent = false;
review.FullTestCount = numel(testResults);
review.FullTestPassed = sum(testPassed);
review.FullTestFailed = sum(testFailed);
review.FullTestIncomplete = sum(testIncomplete);
review.Stage06TestCount = sum(stage06Mask);
review.Stage06TestPassed = sum(testPassed(stage06Mask));
review.WorkspaceScanSummary = scanSummary;
review.Checks = checks;
review.NextStage = 7;
review.NextStageNote = [ ...
    "Stage 7 real robot+sensor read-only dry-run requires the user-supplied " ...
    "pRcmBase and explicit live test preparation. Physical motion remains disabled."];

if options.WriteResults
    timestamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss_SSS'));
    outputDirectory = fullfile(projectRoot, 'results', ...
        "stage06_final_review_" + timestamp);
    mkdir(outputDirectory);
    writeJson(fullfile(outputDirectory, 'summary.json'), review);
    writeJson(fullfile(outputDirectory, 'config_snapshot.json'), cfg);
    writeJson(fullfile(outputDirectory, 'workspace_scan_summary.json'), ...
        scanSummary);
    writetable(workspaceScan.Samples, ...
        fullfile(outputDirectory, 'workspace_samples.csv'));
    writetable(struct2table(checks), ...
        fullfile(outputDirectory, 'checks.csv'));
    testTable = table(testNames, testPassed, testFailed, ...
        testIncomplete, testDurationSec, ...
        'VariableNames', {'Name', 'Passed', 'Failed', ...
        'Incomplete', 'DurationSec'});
    writetable(testTable, fullfile(outputDirectory, 'test_results.csv'));
    writeMarkdown(fullfile(outputDirectory, 'report.md'), review, cfg);
else
    outputDirectory = "";
end

fprintf('Stage 6 final review: %s\n', upper(review.Status));
fprintf('Offline tests: %d / %d passed; Stage 6: %d / %d.\n', ...
    review.FullTestPassed, review.FullTestCount, ...
    review.Stage06TestPassed, review.Stage06TestCount);
fprintf('Workspace: %.2f%% feasible; QP P99 %.3f ms.\n', ...
    100 * scanSummary.FeasibilityRate, ...
    1e3 * scanSummary.OverallTiming.P99Sec);
fprintf('Hardware connections: 0; motion commands: 0.\n');
if strlength(outputDirectory) > 0
    fprintf('Results: %s\n', outputDirectory);
end
end

function passed = namedTestsPassed(names, results, stageMask, patterns)
patterns = string(patterns(:));
matches = false(size(names));
for index = 1:numel(patterns)
    matches = matches | contains(names, patterns(index));
end
matches = matches & stageMask;
passed = nnz(matches) >= numel(patterns) && all(results(matches));
end

function item = makeCheck(name, passed, evidence)
item = struct('Name', string(name), 'Passed', logical(passed), ...
    'Evidence', string(evidence));
end

function writeJson(filePath, value)
try
    encoded = jsonencode(value, 'PrettyPrint', true);
catch
    encoded = jsonencode(value);
end
[fileId, message] = fopen(filePath, 'w');
if fileId < 0
    error('scopeguide:stage06:CannotWriteReview', ...
        'Cannot open %s: %s', filePath, message);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', encoded);
clear cleanup;
end

function writeMarkdown(filePath, review, cfg)
[fileId, message] = fopen(filePath, 'w');
if fileId < 0
    error('scopeguide:stage06:CannotWriteReview', ...
        'Cannot open %s: %s', filePath, message);
end
cleanup = onCleanup(@() fclose(fileId));
scan = review.WorkspaceScanSummary;
fprintf(fileId, '# Stage 6 final review\n\n');
fprintf(fileId, '- Status: **%s**\n', upper(review.Status));
fprintf(fileId, '- Reviewed: %s\n', review.ReviewedAtLocal);
fprintf(fileId, '- Tests: %d/%d passed; Stage 6: %d/%d\n', ...
    review.FullTestPassed, review.FullTestCount, ...
    review.Stage06TestPassed, review.Stage06TestCount);
fprintf(fileId, '- Solver: quadprog; no fallback used\n');
fprintf(fileId, ...
    '- Offline only; hardware connections: 0; motion commands: 0\n');
fprintf(fileId, '- Geometry: `%s`\n\n', review.GeometryUsedForReview);
fprintf(fileId, '## Exit checks\n\n');
fprintf(fileId, '| Check | Passed | Evidence |\n');
fprintf(fileId, '|---|:---:|---|\n');
for index = 1:numel(review.Checks)
    item = review.Checks(index);
    if item.Passed
        mark = 'yes';
    else
        mark = 'no';
    end
    fprintf(fileId, '| %s | %s | %s |\n', ...
        item.Name, mark, item.Evidence);
end
fprintf(fileId, '\n## Workspace and timing\n\n');
fprintf(fileId, '- Feasibility: %d/%d (%.2f%%).\n', ...
    scan.SolvedCount, scan.SampleCount, 100 * scan.FeasibilityRate);
fprintf(fileId, '- Singular safety stops: %d; unexpected failures: %d.\n', ...
    scan.SingularStopCount, scan.UnexpectedFailureCount);
fprintf(fileId, '- QP P50/P95/P99: %.3f / %.3f / %.3f ms.\n', ...
    1e3 * scan.OverallTiming.P50Sec, ...
    1e3 * scan.OverallTiming.P95Sec, ...
    1e3 * scan.OverallTiming.P99Sec);
fprintf(fileId, '- Budget: %.3f ms at %.0f Hz nominal control.\n', ...
    1e3 * cfg.qp.MaximumSolveTimeSec, cfg.runtime.ControlRateHz);
fprintf(fileId, ...
    ['- Timing covers the quadprog call after explicit warm-up; full-loop ' ...
    'timing remains a Stage 7 measurement.\n']);
fprintf(fileId, '- Maximum successful constraint violation: %.3g.\n', ...
    scan.MaximumConstraintViolation);
fprintf(fileId, '\n## Scope boundary\n\n');
fprintf(fileId, ...
    ['This closes Stage 6 mathematical/synthetic-workspace acceptance only. ' ...
    'No real RCM calibration or physical motion readiness is claimed. ' ...
    'Stage 7 requires a supplied pRcmBase and live read-only preparation.\n']);
clear cleanup;
end
