function [review, outputDirectory] = run_stage05_final_review(options)
%RUN_STAGE05_FINAL_REVIEW Run and archive the offline Stage 5 exit audit.
% No robot/sensor adapter is constructed and no hardware command is sent.

arguments
    options.WriteResults (1, 1) logical = true
    options.ReplayMaximumSamples (1, 1) double = 1200
end

projectRoot = string(fileparts(mfilename('fullpath')));
addpath(projectRoot);
addpath(fullfile(projectRoot, 'config'));
cfg = defaultRcmAdmittanceConfig();
testResults = runAllTests();
testNames = string({testResults.Name}).';
testPassed = [testResults.Passed].';
testFailed = [testResults.Failed].';
testIncomplete = [testResults.Incomplete].';
testDurationSec = [testResults.Duration].';
stage05Mask = contains(testNames, ...
    "testStage05ForceOnlyRcmAdmittance/");

[staticReplay, ~] = run_stage05_force_only_admittance_replay( ...
    MaximumSamples=options.ReplayMaximumSamples, WriteResults=false);
parameters = scopeguide.control.deriveForceOnlyAdmittanceParameters(cfg);
authorization = scopeguide.safety.evaluateMotionAuthorization(cfg, "");
parameterIdentityError = max(abs(parameters.VirtualMass - ...
    parameters.Damping .* parameters.TimeConstantSec));
checks = [ ...
    makeCheck("full_offline_regression", ...
        ~isempty(testResults) && all(testPassed), ...
        sprintf('%d/%d passed; failed=%d; incomplete=%d', ...
        sum(testPassed), numel(testResults), sum(testFailed), ...
        sum(testIncomplete))); ...
    makeCheck("stage05_automatic_tests", ...
        sum(stage05Mask) >= 10 && all(testPassed(stage05Mask)), ...
        sprintf('%d Stage 5 tests passed', sum(stage05Mask))); ...
    makeCheck("three_dof_bidirectional_and_roll_zero", ...
        namedTestsPassed(testNames, testPassed, stage05Mask, ...
        "PositiveAndNegativeDirections"), ...
        'both signs tested for pivot1/pivot2/insertion; roll structural zero'); ...
    makeCheck("sensor_wrench_shifted_to_rcm", ...
        namedTestsPassed(testNames, testPassed, stage05Mask, ...
        ["MeasuredWrenchIsShifted", "DirectSensorMomentAndForceMoment"]), ...
        'force and measured moment are combined at the configured RCM'); ...
    makeCheck("speed_acceleration_travel_and_recovery", ...
        namedTestsPassed(testNames, testPassed, stage05Mask, ...
        ["LargeInputRespects", "DesignInputApproaches"]), ...
        'large-input saturation, decay and state synchronization passed'); ...
    makeCheck("measured_dt_and_tip_speed_limit", ...
        namedTestsPassed(testNames, testPassed, stage05Mask, ...
        ["MeasuredDtJitter", "PivotTipSpeedLimit"]), ...
        'dt jitter and variable RCM-tip distance tests passed'); ...
    makeCheck("stage04_reset_and_soft_start_contract", ...
        namedTestsPassed(testNames, testPassed, stage05Mask, ...
        "Stage04ResetAndSoftStart"), ...
        'ResetDynamicState zeros velocity and relative coordinates immediately'); ...
    makeCheck("current_static_record_no_sustained_drift", ...
        staticReplay.Summary.NoSustainedDrift, ...
        sprintf('eligible=%d; tail pivot RMS <= %.6g rad/s; insertion <= %.6g m/s', ...
        staticReplay.Summary.EligibleAdmittanceSampleCount, ...
        staticReplay.Summary.TrailingStaticMetrics.MaximumPivotRmsRadSec, ...
        staticReplay.Summary.TrailingStaticMetrics.MaximumInsertionRmsMSec)); ...
    makeCheck("parameters_explainable", parameterIdentityError < 1e-12, ...
        sprintf('max M-D*tau identity error %.3g', parameterIdentityError)); ...
    makeCheck("implementation_files_present", ...
        implementationFilesPresent(projectRoot), ...
        'basis, mapping, admittance, replay and tests found'); ...
    makeCheck("offline_review_sends_no_motion", ~authorization.Allowed, ...
        sprintf('%d motion gates closed in the offline review', ...
        numel(authorization.FailedGates)))];

review = struct();
review.Stage = 5;
review.ReviewedAtLocal = string(datetime('now', ...
    'TimeZone', 'Asia/Shanghai', ...
    'Format', 'yyyy-MM-dd HH:mm:ss Z'));
review.Status = "not_passed";
review.AllExitChecksPassed = all([checks.Passed]);
if review.AllExitChecksPassed
    review.Status = "passed_offline";
end
review.Scope = "full-wrench 3-DOF RCM admittance math and data replay";
review.OfflineOnly = true;
review.GeometryUsedForReview = ...
    staticReplay.Summary.GeometrySource;
review.RealRcmCalibrationClaimed = false;
review.HardwareConnectionsCreated = false;
review.MotionCommandsSent = false;
review.MomentUsedForControl = true;
review.RollEnabled = false;
review.FullTestCount = numel(testResults);
review.FullTestPassed = sum(testPassed);
review.FullTestFailed = sum(testFailed);
review.FullTestIncomplete = sum(testIncomplete);
review.Stage05TestCount = sum(stage05Mask);
review.Stage05TestPassed = sum(testPassed(stage05Mask));
review.Parameters = parameters;
review.StaticReplaySummary = staticReplay.Summary;
review.Checks = checks;
review.NextStage = 6;
review.NextStageNote = [ ...
    "Stage 6 QP may begin in synthetic/offline geometry. " ...
    "Actual robot-state dry-run still requires supplied pRcmBase; " ...
    "physical motion remains blocked by Stage 3 and safety gates."];

if options.WriteResults
    timestamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss_SSS'));
    outputDirectory = fullfile(projectRoot, 'results', ...
        "stage05_final_review_" + timestamp);
    mkdir(outputDirectory);
    writeJson(fullfile(outputDirectory, 'summary.json'), review);
    writeJson(fullfile(outputDirectory, 'config_snapshot.json'), cfg);
    writeJson(fullfile(outputDirectory, 'static_replay_summary.json'), ...
        staticReplay.Summary);
    writetable(struct2table(checks), ...
        fullfile(outputDirectory, 'checks.csv'));
    testTable = table(testNames, testPassed, testFailed, ...
        testIncomplete, testDurationSec, ...
        'VariableNames', {'Name', 'Passed', 'Failed', ...
        'Incomplete', 'DurationSec'});
    writetable(testTable, fullfile(outputDirectory, 'test_results.csv'));
    writeMarkdown(fullfile(outputDirectory, 'report.md'), review, cfg);
else
    outputDirectory = "";
end

fprintf('Stage 5 final review: %s\n', upper(review.Status));
fprintf('Offline tests: %d / %d passed; Stage 5: %d / %d.\n', ...
    review.FullTestPassed, review.FullTestCount, ...
    review.Stage05TestPassed, review.Stage05TestCount);
fprintf('Hardware connections: 0; motion commands: 0.\n');
if strlength(outputDirectory) > 0
    fprintf('Results: %s\n', outputDirectory);
end
end

function passed = namedTestsPassed(names, results, stageMask, patterns)
patterns = string(patterns(:));
matches = false(size(names));
for index = 1:numel(patterns)
    matches = matches | contains(names, patterns(index));
end
matches = matches & stageMask;
passed = nnz(matches) >= numel(patterns) && all(results(matches));
end

function present = implementationFilesPresent(projectRoot)
files = [ ...
    fullfile(projectRoot, '+scopeguide', '+geometry', ...
        'computeRcmMotionBasis.m'); ...
    fullfile(projectRoot, '+scopeguide', '+control', ...
        'mapWrenchToRcmGeneralizedEffort.m'); ...
    fullfile(projectRoot, '+scopeguide', '+control', ...
        'deriveForceOnlyAdmittanceParameters.m'); ...
    fullfile(projectRoot, '+scopeguide', '+control', ...
        'ForceOnlyRcmAdmittance.m'); ...
    fullfile(projectRoot, 'run_stage05_force_only_admittance_replay.m'); ...
    fullfile(projectRoot, 'tests', ...
        'testStage05ForceOnlyRcmAdmittance.m')];
present = all(arrayfun(@isfile, files));
end

function item = makeCheck(name, passed, evidence)
item = struct('Name', string(name), 'Passed', logical(passed), ...
    'Evidence', string(evidence));
end

function writeJson(filePath, value)
try
    encoded = jsonencode(value, 'PrettyPrint', true);
catch
    encoded = jsonencode(value);
end
[fileId, message] = fopen(filePath, 'w');
if fileId < 0
    error('scopeguide:stage05:CannotWriteReview', ...
        'Cannot open %s: %s', filePath, message);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', encoded);
clear cleanup;
end

function writeMarkdown(filePath, review, cfg)
[fileId, message] = fopen(filePath, 'w');
if fileId < 0
    error('scopeguide:stage05:CannotWriteReview', ...
        'Cannot open %s: %s', filePath, message);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '# Stage 5 final review\n\n');
fprintf(fileId, '- Status: **%s**\n', upper(review.Status));
fprintf(fileId, '- Reviewed: %s\n', review.ReviewedAtLocal);
fprintf(fileId, '- Tests: %d/%d passed; Stage 5: %d/%d\n', ...
    review.FullTestPassed, review.FullTestCount, ...
    review.Stage05TestPassed, review.Stage05TestCount);
fprintf(fileId, ...
    '- Offline only; hardware connections: 0; motion commands: 0\n');
fprintf(fileId, '- Geometry: `%s`\n\n', review.GeometryUsedForReview);
fprintf(fileId, '## Exit checks\n\n');
fprintf(fileId, '| Check | Passed | Evidence |\n');
fprintf(fileId, '|---|:---:|---|\n');
for index = 1:numel(review.Checks)
    item = review.Checks(index);
    if item.Passed
        mark = 'yes';
    else
        mark = 'no';
    end
    fprintf(fileId, '| %s | %s | %s |\n', ...
        item.Name, mark, item.Evidence);
end
fprintf(fileId, '\n## Frozen Stage 5 parameters\n\n');
fprintf(fileId, '- Pivot design force: %.3f N.\n', ...
    cfg.admittance.Pivot.DesignForceN);
fprintf(fileId, '- Nominal lever arm: %.3f m.\n', ...
    cfg.admittance.Pivot.NominalLeverArmM);
fprintf(fileId, '- Pivot target/max: %.3f / %.3f deg/s.\n', ...
    rad2deg(cfg.admittance.Pivot.TargetSteadySpeedRadSec), ...
    rad2deg(cfg.control.PivotMaxRadSec));
fprintf(fileId, '- Insertion target/max: %.3f / %.3f mm/s.\n', ...
    1e3 * cfg.admittance.Insertion.TargetSteadySpeedMSec, ...
    1e3 * cfg.control.InsertionMaxMSec);
fprintf(fileId, '- Pivot/insertion time constants: %.3f / %.3f s.\n', ...
    cfg.admittance.Pivot.TimeConstantSec, ...
    cfg.admittance.Insertion.TimeConstantSec);
fprintf(fileId, '- Relative bounds: %.3f deg and %.3f mm.\n', ...
    rad2deg(cfg.control.RelativePivotLimitRad), ...
    1e3 * cfg.control.RelativeInsertionLimitM);
fprintf(fileId, '- Maximum pivot-tip speed: %.3f mm/s.\n', ...
    1e3 * cfg.admittance.Pivot.MaximumTipSpeedMSec);
fprintf(fileId, '\n## Scope boundary\n\n');
fprintf(fileId, ...
    ['This closes Stage 5 mathematical/data-replay acceptance only. ' ...
    'No real RCM calibration is claimed. Stage 3, real pRcmBase, ' ...
    'RCM bounds and motion safety gates remain open dependencies.\n']);
clear cleanup;
end
