function command = formatDobotServoJCommand( ...
        jointsDeg, t, lookaheadTime, gain)
%FORMATDOBOTSERVOJCOMMAND Build one scalar Dobot ServoJ ASCII command.

joints = double(jointsDeg(:).');
if numel(joints) ~= 6 || any(~isfinite(joints))
    error('ZJFDobotCR5:InvalidServoJJointTarget', ...
        'ServoJ requires six finite joint targets in degrees.');
end

if nargin == 1
    command = sprintf( ...
        'ServoJ(%f,%f,%f,%f,%f,%f)', ...
        joints(1), joints(2), joints(3), ...
        joints(4), joints(5), joints(6));
    return;
end
if nargin ~= 4
    error('ZJFDobotCR5:InvalidServoJArguments', ...
        ['ServoJ formatting accepts joints alone or ' ...
         'joints,t,lookahead_time,gain.']);
end

parameters = double([t, lookaheadTime, gain]);
if any(~isfinite(parameters)) || any(parameters <= 0)
    error('ZJFDobotCR5:InvalidServoJParameters', ...
        'ServoJ t, lookahead_time and gain must be finite and positive.');
end

command = sprintf( ...
    ['ServoJ(%f,%f,%f,%f,%f,%f,' ...
     't=%f,lookahead_time=%f,gain=%f)'], ...
    joints(1), joints(2), joints(3), ...
    joints(4), joints(5), joints(6), ...
    parameters(1), parameters(2), parameters(3));
end
