function validateCartesianAdmittanceDragConfig(cfg)
%VALIDATECARTESIANADMITTANCEDRAGCONFIG Validate the independent no-RCM chain.

validateRcmAdmittanceConfig(cfg);
if ~isfield(cfg, 'cartesianDrag') || ~isstruct(cfg.cartesianDrag) || ...
        ~isscalar(cfg.cartesianDrag)
    error('scopeguide:cartesianDrag:MissingConfiguration', ...
        'cfg.cartesianDrag must be a scalar structure.');
end
c = cfg.cartesianDrag;
required = {'DofMode', 'AllowedDofModes', 'TravelLimitsEnabled', ...
    'TFlangeDragPoint', ...
    'Translation', 'Rotation', 'ControlForceSaturationN', ...
    'ControlMomentSaturationNm', 'VelocityZeroTolerance', 'Qp', ...
    'SetupConfirmationPhrase', 'SafetyThresholdConfirmationPhrase', ...
    'RequireSecondObserver', ...
    'RequireFixtureAndClearanceConfirmation', ...
    'InputHeartbeatTimeoutSec'};
requireFields(c, required, 'cfg.cartesianDrag');
logicalScalar(c.TravelLimitsEnabled, 'TravelLimitsEnabled');

mode = string(c.DofMode);
allowed = string(c.AllowedDofModes(:));
if ~isscalar(mode) || ismissing(mode) || ~any(mode == allowed)
    error('scopeguide:cartesianDrag:InvalidDofMode', ...
        'cfg.cartesianDrag.DofMode is not allowed.');
end
knownModes = ["hold", "translation_z", "translation_xyz", ...
    "rotation_x", "rotation_y", "rotation_z", ...
    "rotation_xyz", "full_6dof"];
if isempty(allowed) || any(~ismember(allowed, knownModes)) || ...
        numel(unique(allowed)) ~= numel(allowed)
    error('scopeguide:cartesianDrag:InvalidAllowedDofModes', ...
        'AllowedDofModes contains an unknown or duplicate mode.');
end
rigidTransform(c.TFlangeDragPoint, ...
    'cfg.cartesianDrag.TFlangeDragPoint');

requireFields(c.Translation, {'DesignForceN', ...
    'TargetSteadySpeedMSec', 'TimeConstantSec', ...
    'MaximumSpeedMSec', 'MaximumAccelerationMSec2', ...
    'RelativeLimitM', 'RecoveryToleranceM'}, ...
    'cfg.cartesianDrag.Translation');
positiveScalar(c.Translation.DesignForceN, 'Translation.DesignForceN');
positiveScalar(c.Translation.TargetSteadySpeedMSec, ...
    'Translation.TargetSteadySpeedMSec');
positiveScalar(c.Translation.TimeConstantSec, ...
    'Translation.TimeConstantSec');
positiveScalar(c.Translation.MaximumSpeedMSec, ...
    'Translation.MaximumSpeedMSec');
positiveScalar(c.Translation.MaximumAccelerationMSec2, ...
    'Translation.MaximumAccelerationMSec2');
positiveVector3(c.Translation.RelativeLimitM, ...
    'Translation.RelativeLimitM');
positiveScalar(c.Translation.RecoveryToleranceM, ...
    'Translation.RecoveryToleranceM');
if c.Translation.RecoveryToleranceM >= ...
        min(double(c.Translation.RelativeLimitM(:)))
    error('scopeguide:cartesianDrag:TranslationRecoveryBandTooLarge', ...
        'Translation recovery tolerance must be below every travel limit.');
end
if c.Translation.TargetSteadySpeedMSec > ...
        c.Translation.MaximumSpeedMSec
    error('scopeguide:cartesianDrag:TranslationTargetAboveLimit', ...
        'Translation target steady speed exceeds its maximum speed.');
end

requireFields(c.Rotation, {'DesignMomentNm', ...
    'TargetSteadySpeedRadSec', 'TimeConstantSec', ...
    'MaximumSpeedRadSec', 'MaximumAccelerationRadSec2', ...
    'RelativeLimitRad', 'RecoveryToleranceRad'}, ...
    'cfg.cartesianDrag.Rotation');
positiveScalar(c.Rotation.DesignMomentNm, 'Rotation.DesignMomentNm');
positiveScalar(c.Rotation.TargetSteadySpeedRadSec, ...
    'Rotation.TargetSteadySpeedRadSec');
positiveScalar(c.Rotation.TimeConstantSec, ...
    'Rotation.TimeConstantSec');
positiveScalar(c.Rotation.MaximumSpeedRadSec, ...
    'Rotation.MaximumSpeedRadSec');
positiveScalar(c.Rotation.MaximumAccelerationRadSec2, ...
    'Rotation.MaximumAccelerationRadSec2');
positiveVector3(c.Rotation.RelativeLimitRad, ...
    'Rotation.RelativeLimitRad');
positiveScalar(c.Rotation.RecoveryToleranceRad, ...
    'Rotation.RecoveryToleranceRad');
if c.Rotation.RecoveryToleranceRad >= ...
        min(double(c.Rotation.RelativeLimitRad(:)))
    error('scopeguide:cartesianDrag:RotationRecoveryBandTooLarge', ...
        'Rotation recovery tolerance must be below every travel limit.');
end
if c.Rotation.TargetSteadySpeedRadSec > ...
        c.Rotation.MaximumSpeedRadSec
    error('scopeguide:cartesianDrag:RotationTargetAboveLimit', ...
        'Rotation target steady speed exceeds its maximum speed.');
end

positiveScalar(c.ControlForceSaturationN, ...
    'ControlForceSaturationN');
positiveScalar(c.ControlMomentSaturationNm, ...
    'ControlMomentSaturationNm');
if c.ControlForceSaturationN >= cfg.safety.FastForceStopN
    error('scopeguide:cartesianDrag:ForceSaturationNotBelowStop', ...
        'Control force saturation must be below FastForceStopN.');
end
if c.ControlMomentSaturationNm >= cfg.safety.FastMomentStopNm
    error('scopeguide:cartesianDrag:MomentSaturationNotBelowStop', ...
        'Control moment saturation must be below FastMomentStopNm.');
end
vTol = double(c.VelocityZeroTolerance(:));
if numel(vTol) ~= 6 || any(~isfinite(vTol)) || any(vTol < 0)
    error('scopeguide:cartesianDrag:InvalidVelocityZeroTolerance', ...
        'VelocityZeroTolerance must contain six finite nonnegative values.');
end

q = c.Qp;
requireFields(q, {'TaskCharacteristicLengthM', 'TaskTrackingWeight', ...
    'JointVelocityRegularization', 'CommandSmoothingWeight', ...
    'JointCenteringGainSecInv', 'JointCenteringMaximumRadSec', ...
    'SingularityStopSigma', 'SingularityFullSpeedSigma'}, ...
    'cfg.cartesianDrag.Qp');
positiveScalar(q.TaskCharacteristicLengthM, ...
    'Qp.TaskCharacteristicLengthM');
positiveScalar(q.TaskTrackingWeight, 'Qp.TaskTrackingWeight');
nonnegativeScalar(q.JointVelocityRegularization, ...
    'Qp.JointVelocityRegularization');
nonnegativeScalar(q.CommandSmoothingWeight, ...
    'Qp.CommandSmoothingWeight');
nonnegativeScalar(q.JointCenteringGainSecInv, ...
    'Qp.JointCenteringGainSecInv');
positiveScalar(q.JointCenteringMaximumRadSec, ...
    'Qp.JointCenteringMaximumRadSec');
positiveScalar(q.SingularityStopSigma, 'Qp.SingularityStopSigma');
positiveScalar(q.SingularityFullSpeedSigma, ...
    'Qp.SingularityFullSpeedSigma');
if q.SingularityStopSigma >= q.SingularityFullSpeedSigma
    error('scopeguide:cartesianDrag:InvalidSingularityBand', ...
        'Singularity stop sigma must be smaller than full-speed sigma.');
end
if strlength(string(c.SetupConfirmationPhrase)) == 0 || ...
        strlength(string(c.SafetyThresholdConfirmationPhrase)) == 0
    error('scopeguide:cartesianDrag:EmptyConfirmationPhrase', ...
        'Cartesian drag confirmation phrases must not be empty.');
end
logicalScalar(c.RequireSecondObserver, 'RequireSecondObserver');
logicalScalar(c.RequireFixtureAndClearanceConfirmation, ...
    'RequireFixtureAndClearanceConfirmation');
positiveScalar(c.InputHeartbeatTimeoutSec, 'InputHeartbeatTimeoutSec');
end

function requireFields(value, fields, name)
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, fields))
    missing = fields(~isfield(value, fields));
    error('scopeguide:cartesianDrag:IncompleteConfiguration', ...
        '%s is missing: %s.', name, strjoin(string(missing), ', '));
end
end

function positiveScalar(value, name)
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value <= 0
    error('scopeguide:cartesianDrag:InvalidPositiveScalar', ...
        '%s must be finite and positive.', name);
end
end

function nonnegativeScalar(value, name)
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
    error('scopeguide:cartesianDrag:InvalidNonnegativeScalar', ...
        '%s must be finite and nonnegative.', name);
end
end

function positiveVector3(value, name)
value = double(value(:));
if numel(value) ~= 3 || any(~isfinite(value)) || any(value <= 0)
    error('scopeguide:cartesianDrag:InvalidPositiveVector', ...
        '%s must contain three finite positive values.', name);
end
end

function logicalScalar(value, name)
if ~islogical(value) || ~isscalar(value)
    error('scopeguide:cartesianDrag:InvalidLogical', ...
        '%s must be a scalar logical.', name);
end
end

function rigidTransform(value, name)
if ~isnumeric(value) || ~isequal(size(value), [4, 4]) || ...
        any(~isfinite(value(:))) || ...
        norm(double(value(4, :)) - [0, 0, 0, 1], inf) > 1e-12
    error('scopeguide:cartesianDrag:InvalidTransform', ...
        '%s must be a finite homogeneous transform.', name);
end
rotation = double(value(1:3, 1:3));
if norm(rotation' * rotation - eye(3), 'fro') > 1e-9 || ...
        abs(det(rotation) - 1) > 1e-9
    error('scopeguide:cartesianDrag:InvalidTransform', ...
        '%s rotation must be right-handed and orthonormal.', name);
end
end
