function validation = validateZeroJointGravityDirection(quaternionWxyz, varargin)
%VALIDATEZEROJOINTGRAVITYDIRECTION Enforce the user-confirmed zero-pose axes.

parser = inputParser;
addParameter(parser, 'RToolFromSensor', diag([-1, -1, 1]));
addParameter(parser, 'GravityBaseMps2', [0, 0, -9.80665]);
addParameter(parser, 'QuaternionConvention', 'base_from_tool');
addParameter(parser, 'ExpectedSensorDirection', [0, -1, 0]);
addParameter(parser, 'ExpectedToolDirection', [0, 1, 0]);
addParameter(parser, 'MaximumDirectionErrorDeg', 10);
parse(parser, varargin{:});
opts = parser.Results;

[actualSensor, actualTool] = gravityDirectionFromDobotQuaternion( ...
    quaternionWxyz, ...
    'RToolFromSensor', opts.RToolFromSensor, ...
    'GravityBaseMps2', opts.GravityBaseMps2, ...
    'QuaternionConvention', opts.QuaternionConvention);
expectedSensor = unitVector(opts.ExpectedSensorDirection, ...
    'ExpectedSensorDirection');
expectedTool = unitVector(opts.ExpectedToolDirection, ...
    'ExpectedToolDirection');
sensorErrorDeg = acosd(max(-1, min(1, dot(actualSensor, expectedSensor))));
toolErrorDeg = acosd(max(-1, min(1, dot(actualTool, expectedTool))));

validation = struct();
validation.actualSensorDirection = actualSensor;
validation.expectedSensorDirection = expectedSensor;
validation.sensorDirectionErrorDeg = sensorErrorDeg;
validation.actualToolDirection = actualTool;
validation.expectedToolDirection = expectedTool;
validation.toolDirectionErrorDeg = toolErrorDeg;
validation.maximumDirectionErrorDeg = opts.MaximumDirectionErrorDeg;
validation.valid = sensorErrorDeg <= opts.MaximumDirectionErrorDeg && ...
    toolErrorDeg <= opts.MaximumDirectionErrorDeg;
if ~validation.valid
    error('calibration:GravityDirectionMismatch', ...
        ['At the zero-joint reference pose, gravity direction mismatch. ' ...
         'Sensor actual/expected: [%+.3f %+.3f %+.3f] / ' ...
         '[%+.3f %+.3f %+.3f], error %.2f deg. ' ...
         'Tool actual/expected: [%+.3f %+.3f %+.3f] / ' ...
         '[%+.3f %+.3f %+.3f], error %.2f deg.'], ...
        actualSensor(1), actualSensor(2), actualSensor(3), ...
        expectedSensor(1), expectedSensor(2), expectedSensor(3), ...
        sensorErrorDeg, ...
        actualTool(1), actualTool(2), actualTool(3), ...
        expectedTool(1), expectedTool(2), expectedTool(3), ...
        toolErrorDeg);
end
end

function value = unitVector(input, name)
value = double(input(:).');
if numel(value) ~= 3 || any(~isfinite(value)) || norm(value) < 1e-9
    error('calibration:InvalidDirection', ...
        '%s must be a finite nonzero three-vector.', name);
end
value = value / norm(value);
end
