classdef MockDobotMotionBackend < handle
    %MOCKDOBOTMOTIONBACKEND Offline Stage 8 ServoJ test double.

    properties
        IsConnected = false
        ConnectCallCount = uint64(0)
        DisconnectCallCount = uint64(0)
        ServoJCallCount = uint64(0)
        EnableCallCount = uint64(0)
        SetSpeedRatioCallCount = uint64(0)
        DisableCallCount = uint64(0)
        LastEnablePayloadKg = NaN
        LastSpeedRatioPercent = NaN
        EnableChangesMode = true
        Snapshot
        LastServoTargetDeg = nan(1, 6)
        LastServoTimeSec = NaN
        LastServoLookaheadTime = NaN
        LastServoGain = NaN
        LastServoCommand = ""
        ServoResponse = "0,{},ServoJ();"
        ServoResponseDelaySec = 0
        ThrowOnServo = false
        LogEveryCommand = true
        LastMoveCommandDiagnostics = struct()
        LastAsynchronousMoveDiagnostics = struct()
    end

    methods
        function obj = MockDobotMotionBackend(snapshot)
            obj.Snapshot = snapshot;
        end

        function Connect(obj)
            obj.ConnectCallCount = obj.ConnectCallCount + uint64(1);
            obj.IsConnected = true;
        end

        function Disconnect(obj)
            obj.DisconnectCallCount = obj.DisconnectCallCount + uint64(1);
            obj.IsConnected = false;
        end

        function snapshot = GetStateSnapshot(obj)
            if ~obj.IsConnected
                error('ZJFDobotCR5:NoFeedback', 'Mock is disconnected.');
            end
            snapshot = obj.Snapshot;
        end

        function response = Enable(obj, payloadKg)
            obj.EnableCallCount = obj.EnableCallCount + uint64(1);
            obj.LastEnablePayloadKg = double(payloadKg);
            if obj.EnableChangesMode
                obj.Snapshot.robotMode = "ENABLE";
            end
            response = '';
        end

        function response = SetSpeedRatio(obj, ratioPercent)
            obj.SetSpeedRatioCallCount = ...
                obj.SetSpeedRatioCallCount + uint64(1);
            obj.LastSpeedRatioPercent = double(ratioPercent);
            obj.Snapshot.currentSpeedRatio = double(ratioPercent);
            response = '';
        end

        function response = Disable(obj)
            obj.DisableCallCount = obj.DisableCallCount + uint64(1);
            obj.Snapshot.robotMode = "DISABLED";
            response = '';
        end

        function response = ServoJ(obj, jointsDeg, varargin)
            obj.ServoJCallCount = obj.ServoJCallCount + uint64(1);
            obj.LastServoTargetDeg = double(jointsDeg(:)).';
            if isempty(varargin)
                obj.LastServoTimeSec = NaN;
                obj.LastServoLookaheadTime = NaN;
                obj.LastServoGain = NaN;
                obj.LastServoCommand = "ServoJ(mock)";
            elseif numel(varargin) == 3
                obj.LastServoTimeSec = double(varargin{1});
                obj.LastServoLookaheadTime = double(varargin{2});
                obj.LastServoGain = double(varargin{3});
                obj.LastServoCommand = string(sprintf([ ...
                    'ServoJ(mock,t=%.6f,lookahead_time=%.6f,' ...
                    'gain=%.6f)'], obj.LastServoTimeSec, ...
                    obj.LastServoLookaheadTime, obj.LastServoGain));
            else
                error('scopeguide:tests:InvalidMockServoArguments', ...
                    'Mock ServoJ expects no dynamic parameters or all three.');
            end
            if obj.ThrowOnServo
                obj.LastMoveCommandDiagnostics = struct( ...
                    'Mode', "legacy_immediate_optional_response", ...
                    'ResponseExpected', false, ...
                    'ReplyDeadlinePolicy', ...
                        "single_immediate_read_no_wait", ...
                    'Command', obj.LastServoCommand, ...
                    'WriteFailed', true, ...
                    'PendingResponseCount', 0, ...
                    'FaultIdentifier', ...
                        "scopeguide:tests:InjectedServoFailure");
                obj.LastAsynchronousMoveDiagnostics = ...
                    obj.LastMoveCommandDiagnostics;
                error('scopeguide:tests:InjectedServoFailure', ...
                    'Injected ServoJ failure.');
            end
            if obj.ServoResponseDelaySec > 0
                pause(obj.ServoResponseDelaySec);
            end
            obj.Snapshot.jointAnglesDeg = obj.LastServoTargetDeg;
            obj.Snapshot.feedbackSequence = ...
                obj.Snapshot.feedbackSequence + uint64(1);
            response = char(obj.ServoResponse);
            obj.LastMoveCommandDiagnostics = struct( ...
                'Mode', "legacy_immediate_optional_response", ...
                'ResponseExpected', false, ...
                'ReplyDeadlinePolicy', ...
                    "single_immediate_read_no_wait", ...
                'Command', obj.LastServoCommand, ...
                'WriteFailed', false, ...
                'PendingResponseCount', 0, ...
                'FaultIdentifier', "");
            obj.LastAsynchronousMoveDiagnostics = struct( ...
                'Mode', "legacy_immediate_optional_response", ...
                'ResponseExpected', false, ...
                'ReplyDeadlinePolicy', ...
                    "single_immediate_read_no_wait", ...
                'CommandSentCount', double(obj.ServoJCallCount), ...
                'AcknowledgedCount', 0, ...
                'OptionalResponseCount', ...
                    double(strlength(string(response)) > 0), ...
                'LateResponseCount', 0, 'ErrorCount', 0, ...
                'PendingResponseCount', 0, ...
                'MaximumObservedPendingResponses', 0, ...
                'MaximumAllowedPendingResponses', 0, ...
                'NominalResponseDeadlineSec', NaN, ...
                'HardResponseTimeoutSec', NaN, ...
                'ResponseLatenciesSec', zeros(0, 1), ...
                'OldestPendingAgeSec', NaN, ...
                'FaultIdentifier', "", 'FaultMessage', "", ...
                'LastResponse', obj.LastMoveCommandDiagnostics);
        end

        function result = ServoJNonblocking(obj, jointsDeg, varargin)
            response = obj.ServoJ(jointsDeg, varargin{:});
            diagnostics = obj.LastMoveCommandDiagnostics;
            if isempty(fieldnames(diagnostics))
                diagnostics = struct( ...
                    'Mode', "nonblocking_no_reply_expected", ...
                    'ResponseExpected', false, ...
                    'ReplyDeadlinePolicy', ...
                        "not_applied_to_servoj", ...
                    'CommandSentCount', double(obj.ServoJCallCount), ...
                    'AcknowledgedCount', 0, ...
                    'OptionalResponseCount', 0, ...
                    'LateResponseCount', 0, 'ErrorCount', 0, ...
                    'PendingResponseCount', 0, ...
                    'MaximumObservedPendingResponses', 0, ...
                    'MaximumAllowedPendingResponses', 0, ...
                    'NominalResponseDeadlineSec', NaN, ...
                    'HardResponseTimeoutSec', NaN, ...
                    'ResponseLatenciesSec', zeros(0, 1), ...
                    'OldestPendingAgeSec', NaN, ...
                    'FaultIdentifier', "", 'FaultMessage', "", ...
                    'LastResponse', struct());
            end
            obj.LastAsynchronousMoveDiagnostics = diagnostics;
            result = struct('Mode', "nonblocking_no_reply_expected", ...
                'ResponseExpected', false, ...
                'ReplyDeadlinePolicy', "not_applied_to_servoj", ...
                'Sequence', double(obj.ServoJCallCount), ...
                'Command', obj.LastServoCommand, 'Submitted', true, ...
                'WriteElapsedSec', 0.0001, ...
                'ResponseConfirmed', false, ...
                'PendingResponseCount', 0, ...
                'MockResponse', string(response));
        end

        function diagnostics = PollMoveResponses(obj)
            diagnostics = obj.GetAsynchronousMoveDiagnostics();
        end

        function diagnostics = GetAsynchronousMoveDiagnostics(obj)
            diagnostics = obj.LastAsynchronousMoveDiagnostics;
            if isempty(fieldnames(diagnostics))
                diagnostics = struct( ...
                    'Mode', "nonblocking_no_reply_expected", ...
                    'ResponseExpected', false, ...
                    'ReplyDeadlinePolicy', ...
                        "not_applied_to_servoj", ...
                    'CommandSentCount', 0, 'AcknowledgedCount', 0, ...
                    'OptionalResponseCount', 0, ...
                    'LateResponseCount', 0, 'ErrorCount', 0, ...
                    'PendingResponseCount', 0, ...
                    'MaximumObservedPendingResponses', 0, ...
                    'MaximumAllowedPendingResponses', 0, ...
                    'NominalResponseDeadlineSec', NaN, ...
                    'HardResponseTimeoutSec', NaN, ...
                    'ResponseLatenciesSec', zeros(0, 1), ...
                    'OldestPendingAgeSec', NaN, ...
                    'FaultIdentifier', "", 'FaultMessage', "", ...
                    'LastResponse', struct());
            end
        end
    end
end
