function tests = testServoJCommunicationDiagnostic
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = fileparts(fileparts(mfilename('fullpath')));
addpath(root);
addpath(fullfile(root, 'robot'));
testCase.TestData.Root = root;
end

function testMinimalCommandMatchesCurrentStage08Syntax(testCase)
command = scopeguide.diagnostics.formatServoJDiagnosticCommand( ...
    [1, 2, 3, 4, 5, 6], "scopeguide_minimal");
verifyEqual(testCase, command, ...
    "ServoJ(1.000000,2.000000,3.000000,4.000000,5.000000,6.000000)");
end

function testParameterizedCommandMatchesLegacyProjectSyntax(testCase)
command = scopeguide.diagnostics.formatServoJDiagnosticCommand( ...
    [1, 2, 3, 4, 5, 6], "legacy_parameterized", 0.04, 60, 400);
expected = ...
    "ServoJ(1.000000,2.000000,3.000000,4.000000,5.000000,6.000000," + ...
    "t=0.040000,lookahead_time=60.000000,gain=400.000000)";
verifyEqual(testCase, command, expected);
end

function testUnknownProfileRejected(testCase)
verifyError(testCase, @() ...
    scopeguide.diagnostics.formatServoJDiagnosticCommand( ...
    zeros(1, 6), "unknown"), ...
    'scopeguide:servoJDiagnostic:UnknownCommandProfile');
end

function testAsciiResponseFramingHandlesPartialAndCoalescedReads(testCase)
firstPart = uint8('0,{},ServoJ(1,2,3');
[frames, remainder] = ...
    scopeguide.diagnostics.extractDobotAsciiFrames([], firstPart);
verifyEmpty(testCase, frames);
verifyEqual(testCase, remainder, firstPart);

secondPart = uint8([',4,5,6);', ...
    '-20000,{},ServoJ(1,2,3);', ...
    '0,{},ServoJ(partial']);
[frames, remainder] = ...
    scopeguide.diagnostics.extractDobotAsciiFrames(remainder, secondPart);
verifyEqual(testCase, frames, [ ...
    "0,{},ServoJ(1,2,3,4,5,6);"; ...
    "-20000,{},ServoJ(1,2,3);"]);
verifyEqual(testCase, char(remainder), '0,{},ServoJ(partial');
end

function testPhysicalDiagnosticFailsClosedBeforeNetworkAccess(testCase)
verifyError(testCase, @() run_servoj_communication_diagnostic( ...
    ArmPhysicalMotion=false, ShowFigure=false, WriteResults=false), ...
    'scopeguide:servoJDiagnostic:PhysicalMotionNotArmed');
end

function testConfirmationMustMatchExactly(testCase)
verifyError(testCase, @() run_servoj_communication_diagnostic( ...
    ArmPhysicalMotion=true, MotionConfirmation="wrong", ...
    FixtureAndClearanceConfirmed=true, SecondObserverPresent=true, ...
    ShowFigure=false, WriteResults=false), ...
    'scopeguide:servoJDiagnostic:ConfirmationMismatch');
end
