function tests = testThreePoseForceDiagnostic
tests = functiontests(localfunctions);
end

function testDefaultCartesianCandidatePlan(testCase)
current = [100, -200, 300, 40, -50, 60];
plan = scopeguide.diagnostics.buildThreePoseCartesianTargets( ...
    current, [8 0 0], [0 8 0], 15);

verifyEqual(testCase, plan.TargetCartesianPose, [ ...
    current; ...
    current + [0 0 0 8 0 0]; ...
    current + [0 0 0 0 8 0]; ...
    current], 'AbsTol', 0);
verifyLessThanOrEqual(testCase, plan.OrientationTransitionDeg, ...
    [8; 12; 8] + 1e-12);
verifyEqual(testCase, plan.TargetCartesianPose(:, 1:3), ...
    repmat(current(1:3), 4, 1), 'AbsTol', 0);
verifyEqual(testCase, plan.Labels, ...
    ["A_initial"; "B"; "C"; "A_return"]);
verifyEqual(testCase, plan.ControllerPoseReferenceAssumption, "flange");
end

function testLargeCartesianTransitionRejected(testCase)
verifyError(testCase, @() ...
    scopeguide.diagnostics.buildThreePoseCartesianTargets( ...
        zeros(1, 6), [30 0 0], [0 0 0], 25), ...
    'scopeguide:diagnostics:TransitionTooLarge');
end

function testWrappedCartesianTransitionNearBoundary(testCase)
plan = scopeguide.diagnostics.buildThreePoseCartesianTargets( ...
    [0 0 0 179 0 0], [4 0 0], [2 0 0], 5);
verifyEqual(testCase, plan.OrientationTransitionDeg, [4; 2; 2], ...
    'AbsTol', 1e-12);
verifyEqual(testCase, plan.TargetCartesianPose(2, 4), -177, ...
    'AbsTol', 1e-12);
end

function testRepeatedRobotFeedbackDoesNotCountAsTwoMovingFrames(testCase)
previous = uint64(0);
count = 0;
[previous, count, isNew] = ...
    scopeguide.diagnostics.updateUniqueMotionCounter( ...
    previous, count, uint64(10), true);
verifyTrue(testCase, isNew);
verifyEqual(testCase, count, 1);

[previous, count, isNew] = ...
    scopeguide.diagnostics.updateUniqueMotionCounter( ...
    previous, count, uint64(10), true);
verifyFalse(testCase, isNew);
verifyEqual(testCase, count, 1);

[previous, count, isNew] = ...
    scopeguide.diagnostics.updateUniqueMotionCounter( ...
    previous, count, uint64(11), true);
verifyTrue(testCase, isNew);
verifyEqual(testCase, count, 2);

[~, count, isNew] = scopeguide.diagnostics.updateUniqueMotionCounter( ...
    previous, count, uint64(12), false);
verifyTrue(testCase, isNew);
verifyEqual(testCase, count, 0);
end
