function tests = testDeadzoneThresholdIdentification
tests = functiontests(localfunctions);
end

function setupOnce(~)
root = fileparts(fileparts(mfilename('fullpath')));
addpath(root);
end

function testCandidateUsesWorstPosePercentileMarginAndRounding(testCase)
signals = syntheticSignals();
report = scopeguide.force.estimateDeadzoneThresholds(signals, ...
    Percentile=99.5, ForceMarginN=0.15, MomentMarginNm=0.015, ...
    ForceRoundingN=0.05, MomentRoundingNm=0.005, ...
    CurrentForceDeadzoneN=1.3, CurrentMomentDeadzoneNm=0.18, ...
    MinimumEligibleSamples=100);

verifyTrue(testCase, report.Valid);
verifyEqual(testCase, report.CandidateForceDeadzoneN, 0.80, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, report.CandidateMomentDeadzoneNm, 0.045, ...
    'AbsTol', 1e-12);
verifyEqual(testCase, report.SuggestedForceReleaseThresholdN, 0.64, ...
    'AbsTol', 1e-12);

rows = report.Excursions.PoseIndex == 3 & ...
    report.Excursions.Signal == "force" & ...
    report.Excursions.ThresholdKind == "candidate";
verifyEqual(testCase, report.Excursions.ExcursionCount(rows), 1);
verifyEqual(testCase, report.Excursions.MaxDurationSec(rows), 0.04, ...
    'AbsTol', 1e-10);
verifyEqual(testCase, report.SuggestedActivationHoldSec, 0.06, ...
    'AbsTol', 1e-12);
end

function testLowEligibleRatioIsReportedInvalid(testCase)
signals = syntheticSignals();
poseThree = signals.PoseIndex == 3;
indices = find(poseThree);
signals.AnalysisEligible(indices(1:150)) = false;
report = scopeguide.force.estimateDeadzoneThresholds(signals, ...
    MinimumEligibleRatio=0.90, MinimumEligibleSamples=100);

verifyFalse(testCase, report.Valid);
verifyEqual(testCase, report.Status, "insufficient_eligible_ratio");
end

function testLegacyAxisSuffixesAreCanonicalizedWithoutChangingValues(testCase)
signals = syntheticSignals();
legacyNames = ["ExternalFX", "ExternalFY", "ExternalFZ", ...
    "ExternalTX", "ExternalTY", "ExternalTZ", ...
    "SlowFX", "SlowFY", "SlowFZ", ...
    "SlowTX", "SlowTY", "SlowTZ"];
canonicalNames = ["ExternalFx", "ExternalFy", "ExternalFz", ...
    "ExternalTx", "ExternalTy", "ExternalTz", ...
    "SlowFx", "SlowFy", "SlowFz", ...
    "SlowTx", "SlowTy", "SlowTz"];
expected = signals{:, canonicalNames};
for index = 1:numel(canonicalNames)
    location = find(string(signals.Properties.VariableNames) == ...
        canonicalNames(index), 1);
    signals.Properties.VariableNames{location} = char(legacyNames(index));
end

[normalized, renamed] = ...
    scopeguide.force.normalizeDeadzoneSignalColumnNames(signals);

verifyEqual(testCase, normalized{:, canonicalNames}, expected);
verifyEqual(testCase, size(renamed, 1), numel(canonicalNames));
verifyTrue(testCase, all(ismember(canonicalNames, ...
    string(normalized.Properties.VariableNames))));
verifyFalse(testCase, any(ismember(legacyNames, ...
    string(normalized.Properties.VariableNames))));
end

function signals = syntheticSignals()
samplesPerPose = 1000;
poseIndex = repelem((1:3).', samplesPerPose);
poseLabel = "pose" + compose('%02d', poseIndex);
sampleTimeSec = (0:numel(poseIndex)-1).' * 0.01;
analysisEligible = true(size(poseIndex));

slowFx = repelem([0.20; 0.42; 0.61], samplesPerPose);
slowTx = repelem([0.010; 0.020; 0.027], samplesPerPose);
poseThreeStart = 2 * samplesPerPose;
slowFx(poseThreeStart + (501:504)) = 1.0;
zerosColumn = zeros(size(poseIndex));

signals = table(poseIndex, poseLabel, sampleTimeSec, ...
    analysisEligible, ...
    slowFx, zerosColumn, zerosColumn, ...
    slowTx, zerosColumn, zerosColumn, ...
    slowFx, zerosColumn, zerosColumn, ...
    slowTx, zerosColumn, zerosColumn, ...
    'VariableNames', {'PoseIndex', 'PoseLabel', 'SampleTimeSec', ...
    'AnalysisEligible', ...
    'ExternalFx', 'ExternalFy', 'ExternalFz', ...
    'ExternalTx', 'ExternalTy', 'ExternalTz', ...
    'SlowFx', 'SlowFy', 'SlowFz', ...
    'SlowTx', 'SlowTy', 'SlowTz'});
end
