function validateRcmAdmittanceConfig(cfg)
%VALIDATERCMADMITTANCECONFIG Validate units, shapes and safety invariants.

requiredTopLevel = {'meta', 'runtime', 'robot', 'sensor', 'handle', ...
    'tool', 'kinematics', 'force', 'control', 'admittance', 'qp', 'rcm', ...
    'safety', 'stage08', 'logging'};
for index = 1:numel(requiredTopLevel)
    requireField(cfg, requiredTopLevel{index}, 'cfg');
end

validModes = ["offline_replay", "live_dry_run", ...
    "fixture_motion", "phantom_motion"];
mode = scalarString(cfg.runtime.Mode, 'cfg.runtime.Mode');
if ~any(mode == validModes)
    error('scopeguide:config:InvalidMode', ...
        'runtime.Mode must be one of: %s.', strjoin(validModes, ', '));
end

positiveScalar(cfg.runtime.ControlRateHz, 'cfg.runtime.ControlRateHz');
positiveScalar(cfg.runtime.NominalDtSec, 'cfg.runtime.NominalDtSec');
positiveScalar(cfg.runtime.MaximumDtSec, 'cfg.runtime.MaximumDtSec');
expectedNominalDtSec = 1 / cfg.runtime.ControlRateHz;
if abs(cfg.runtime.NominalDtSec - expectedNominalDtSec) > ...
        100 * eps(expectedNominalDtSec)
    error('scopeguide:config:InconsistentControlRate', ...
        ['NominalDtSec must equal 1 / ControlRateHz; configured values ' ...
        'are %.9g s and %.9g Hz.'], ...
        cfg.runtime.NominalDtSec, cfg.runtime.ControlRateHz);
end
if cfg.runtime.MaximumDtSec < cfg.runtime.NominalDtSec
    error('scopeguide:config:InvalidControlPeriod', ...
        'MaximumDtSec must be greater than or equal to NominalDtSec.');
end

logicalScalar(cfg.robot.EnableMotion, 'cfg.robot.EnableMotion');
logicalScalar(cfg.robot.DryRun, 'cfg.robot.DryRun');
logicalScalar(cfg.robot.RequireTypedConfirmation, ...
    'cfg.robot.RequireTypedConfirmation');
requireField(cfg.robot, 'ServoJLookaheadTime', 'cfg.robot');
requireField(cfg.robot, 'ServoJGain', 'cfg.robot');
positiveScalar(cfg.robot.ServoJLookaheadTime, ...
    'cfg.robot.ServoJLookaheadTime');
positiveScalar(cfg.robot.ServoJGain, 'cfg.robot.ServoJGain');
if cfg.robot.ServoJLookaheadTime < 20 || ...
        cfg.robot.ServoJLookaheadTime > 100
    error('scopeguide:config:InvalidServoJLookaheadTime', ...
        'ServoJLookaheadTime must lie in the documented [20, 100] range.');
end
if cfg.robot.ServoJGain < 200 || cfg.robot.ServoJGain > 1000
    error('scopeguide:config:InvalidServoJGain', ...
        'ServoJGain must lie in the documented [200, 1000] range.');
end
if cfg.runtime.NominalDtSec < 0.02
    error('scopeguide:config:ServoJControlPeriodTooShort', ...
        ['NominalDtSec is used as ServoJ t and must be at least the ' ...
         'documented minimum of 0.02 seconds.']);
end
positiveScalar(cfg.robot.ExpectedFeedbackRateHz, ...
    'cfg.robot.ExpectedFeedbackRateHz');
positiveScalar(cfg.robot.FeedbackStaleSec, 'cfg.robot.FeedbackStaleSec');
positiveScalar(cfg.robot.InitialFeedbackTimeoutSec, ...
    'cfg.robot.InitialFeedbackTimeoutSec');
positiveScalar(cfg.robot.JointPositionScaleToRad, ...
    'cfg.robot.JointPositionScaleToRad');
positiveScalar(cfg.robot.JointVelocityScaleToRadSec, ...
    'cfg.robot.JointVelocityScaleToRadSec');
positiveScalar(cfg.robot.ControllerPoseTranslationScaleToM, ...
    'cfg.robot.ControllerPoseTranslationScaleToM');
positiveScalar(cfg.robot.ControllerPoseAngleScaleToRad, ...
    'cfg.robot.ControllerPoseAngleScaleToRad');
positiveScalar(cfg.robot.TcpLinearVelocityScaleToMSec, ...
    'cfg.robot.TcpLinearVelocityScaleToMSec');
positiveScalar(cfg.robot.TcpAngularVelocityScaleToRadSec, ...
    'cfg.robot.TcpAngularVelocityScaleToRadSec');
validPoseReferences = ["unknown", "flange", "endoscope"];
if ~any(scalarString(cfg.robot.ControllerPoseReference, ...
        'cfg.robot.ControllerPoseReference') == validPoseReferences)
    error('scopeguide:config:InvalidControllerPoseReference', ...
        'ControllerPoseReference must be unknown, flange or endoscope.');
end
logicalScalar(cfg.robot.ControllerPoseUnitsVerified, ...
    'cfg.robot.ControllerPoseUnitsVerified');
logicalScalar(cfg.robot.ModelVerified, 'cfg.robot.ModelVerified');
logicalScalar(cfg.robot.ServoTimingVerified, 'cfg.robot.ServoTimingVerified');

positiveScalar(cfg.sensor.SampleRateHz, 'cfg.sensor.SampleRateHz');
positiveScalar(cfg.sensor.StaleSec, 'cfg.sensor.StaleSec');
positiveScalar(cfg.sensor.MaximumReadDurationSec, ...
    'cfg.sensor.MaximumReadDurationSec');
nonnegativeScalar(cfg.sensor.FutureTimestampToleranceSec, ...
    'cfg.sensor.FutureTimestampToleranceSec');
logicalScalar(cfg.sensor.StatusCheckEnabled, ...
    'cfg.sensor.StatusCheckEnabled');
positiveScalar(cfg.handle.StaleSec, 'cfg.handle.StaleSec');
nonnegativeScalar(cfg.handle.FutureTimestampToleranceSec, ...
    'cfg.handle.FutureTimestampToleranceSec');
nonnegativeScalar(cfg.handle.RisingDebounceSec, ...
    'cfg.handle.RisingDebounceSec');
nonnegativeScalar(cfg.handle.SoftStartSec, 'cfg.handle.SoftStartSec');
nonnegativeScalar(cfg.handle.KeyboardReleaseConfirmSec, ...
    'cfg.handle.KeyboardReleaseConfirmSec');
if cfg.handle.KeyboardReleaseConfirmSec > 0.050
    error('scopeguide:config:KeyboardReleaseConfirmationTooLong', ...
        ['KeyboardReleaseConfirmSec must not exceed 50 ms. ' ...
        'Keyboard input is for dry-run only.']);
end
positiveScalar(cfg.handle.KeyboardRepeatWatchdogSec, ...
    'cfg.handle.KeyboardRepeatWatchdogSec');
if cfg.handle.KeyboardRepeatWatchdogSec <= ...
        cfg.handle.KeyboardReleaseConfirmSec || ...
        cfg.handle.KeyboardRepeatWatchdogSec > 0.500
    error('scopeguide:config:InvalidKeyboardRepeatWatchdog', ...
        ['KeyboardRepeatWatchdogSec must exceed the release confirmation ' ...
        'window and must not exceed 500 ms.']);
end
logicalScalar(cfg.handle.SoftwareInputSupportsPhysicalMotion, ...
    'cfg.handle.SoftwareInputSupportsPhysicalMotion');

validateTransform(cfg.tool.TFlangeEndoscope, ...
    'cfg.tool.TFlangeEndoscope');
validateTransform(cfg.tool.TFlangeSensor, ...
    'cfg.tool.TFlangeSensor');
optionalScalarString(cfg.tool.SensorOriginSource, ...
    'cfg.tool.SensorOriginSource');
finiteVector(cfg.tool.TipInEndoscopeM, 3, ...
    'cfg.tool.TipInEndoscopeM');
axisVector = finiteVector(cfg.tool.ShaftAxisEndoscope, 3, ...
    'cfg.tool.ShaftAxisEndoscope');
if abs(norm(axisVector) - 1) > 1e-10
    error('scopeguide:config:InvalidShaftAxis', ...
        'tool.ShaftAxisEndoscope must be a unit vector.');
end
if ~isscalar(cfg.tool.InsertionAxisSign) || ...
        ~any(cfg.tool.InsertionAxisSign == [-1, 1])
    error('scopeguide:config:InvalidInsertionAxisSign', ...
        'tool.InsertionAxisSign must be +1 or -1.');
end
logicalScalar(cfg.tool.GeometryVerified, 'cfg.tool.GeometryVerified');

if scalarString(cfg.kinematics.Convention, ...
        'cfg.kinematics.Convention') ~= "standard-DH"
    error('scopeguide:config:InvalidDhConvention', ...
        'Only standard-DH is supported by the declared model.');
end
finiteVector(cfg.kinematics.ThetaOffsetRad, 6, ...
    'cfg.kinematics.ThetaOffsetRad');
finiteVector(cfg.kinematics.DM, 6, 'cfg.kinematics.DM');
finiteVector(cfg.kinematics.AM, 6, 'cfg.kinematics.AM');
finiteVector(cfg.kinematics.AlphaRad, 6, ...
    'cfg.kinematics.AlphaRad');
positiveScalar(cfg.kinematics.MaximumAbsJointAngleRad, ...
    'cfg.kinematics.MaximumAbsJointAngleRad');
jointLower = finiteVector(cfg.kinematics.JointLowerLimitRad, 6, ...
    'cfg.kinematics.JointLowerLimitRad');
jointUpper = finiteVector(cfg.kinematics.JointUpperLimitRad, 6, ...
    'cfg.kinematics.JointUpperLimitRad');
if any(jointLower >= jointUpper)
    error('scopeguide:config:InvalidJointLimits', ...
        'Every joint lower limit must be smaller than its upper limit.');
end
optionalScalarString(cfg.kinematics.JointLimitSource, ...
    'cfg.kinematics.JointLimitSource');

positiveScalar(cfg.force.FastCutoffHz, 'cfg.force.FastCutoffHz');
positiveScalar(cfg.force.ControlCutoffHz, 'cfg.force.ControlCutoffHz');
if cfg.force.ControlCutoffHz >= cfg.force.FastCutoffHz
    error('scopeguide:config:InvalidFilterCutoffs', ...
        'ControlCutoffHz must be smaller than FastCutoffHz.');
end
if cfg.force.FastCutoffHz >= cfg.sensor.SampleRateHz / 2
    error('scopeguide:config:InvalidFilterCutoffs', ...
        'FastCutoffHz must be below the sensor Nyquist frequency.');
end
positiveScalar(cfg.force.ForceDeadzoneN, 'cfg.force.ForceDeadzoneN');
positiveScalar(cfg.force.MomentDeadzoneNm, ...
    'cfg.force.MomentDeadzoneNm');
positiveScalar(cfg.force.NeutralForceLimitN, ...
    'cfg.force.NeutralForceLimitN');
positiveScalar(cfg.force.NeutralMomentLimitNm, ...
    'cfg.force.NeutralMomentLimitNm');
if ~isnumeric(cfg.force.DeadzoneReleaseRatio) || ...
        ~isscalar(cfg.force.DeadzoneReleaseRatio) || ...
        ~isfinite(cfg.force.DeadzoneReleaseRatio) || ...
        cfg.force.DeadzoneReleaseRatio <= 0 || ...
        cfg.force.DeadzoneReleaseRatio > 1
    error('scopeguide:config:InvalidDeadzoneReleaseRatio', ...
        'force.DeadzoneReleaseRatio must lie in (0, 1].');
end
logicalScalar(cfg.force.AutomaticBaselineEnabled, ...
    'cfg.force.AutomaticBaselineEnabled');
logicalScalar(cfg.force.ParametersValidated, ...
    'cfg.force.ParametersValidated');
validateBaselineConfig(cfg.force.Baseline);

if ~isscalar(cfg.control.DofCount) || cfg.control.DofCount ~= 3
    error('scopeguide:config:InvalidDofCount', ...
        'The current RCM wrench implementation requires a 3-DOF controller.');
end
logicalScalar(cfg.control.EnableRoll, 'cfg.control.EnableRoll');
if cfg.control.EnableRoll || cfg.control.RollMaxRadSec ~= 0
    error('scopeguide:config:RollNotAvailable', ...
        'Roll must remain disabled before the optional 4-DOF stage.');
end
positiveScalar(cfg.control.PivotMaxRadSec, ...
    'cfg.control.PivotMaxRadSec');
positiveScalar(cfg.control.InsertionMaxMSec, ...
    'cfg.control.InsertionMaxMSec');
positiveScalar(cfg.control.RelativePivotLimitRad, ...
    'cfg.control.RelativePivotLimitRad');
positiveScalar(cfg.control.RelativeInsertionLimitM, ...
    'cfg.control.RelativeInsertionLimitM');
positiveScalar(cfg.control.RelativePivotRecoveryToleranceRad, ...
    'cfg.control.RelativePivotRecoveryToleranceRad');
positiveScalar(cfg.control.RelativeInsertionRecoveryToleranceM, ...
    'cfg.control.RelativeInsertionRecoveryToleranceM');
if cfg.control.RelativePivotRecoveryToleranceRad >= ...
        cfg.control.RelativePivotLimitRad
    error('scopeguide:config:PivotRecoveryBandTooLarge', ...
        ['control.RelativePivotRecoveryToleranceRad must be below ' ...
         'control.RelativePivotLimitRad.']);
end
if cfg.control.RelativeInsertionRecoveryToleranceM >= ...
        cfg.control.RelativeInsertionLimitM
    error('scopeguide:config:InsertionRecoveryBandTooLarge', ...
        ['control.RelativeInsertionRecoveryToleranceM must be below ' ...
         'control.RelativeInsertionLimitM.']);
end
positiveFiniteVector(cfg.control.MaximumJointCommandRadSec, 6, ...
    'cfg.control.MaximumJointCommandRadSec');
positiveFiniteVector(cfg.control.MaximumJointAccelerationRadSec2, 6, ...
    'cfg.control.MaximumJointAccelerationRadSec2');
positiveFiniteVector(cfg.control.MaximumTargetStateErrorRad, 6, ...
    'cfg.control.MaximumTargetStateErrorRad');

validateAdmittanceConfig(cfg.admittance, cfg.control);
validateQpConfig(cfg.qp, cfg.runtime, cfg.kinematics);

validRcmModes = ["hard", "soft", "hybrid"];
if ~any(scalarString(cfg.rcm.Mode, 'cfg.rcm.Mode') == validRcmModes)
    error('scopeguide:config:InvalidRcmMode', ...
        'rcm.Mode must be hard, soft or hybrid.');
end
validateRcmPoint(cfg.rcm.PointBaseM);
if scalarString(cfg.rcm.PointFrame, 'cfg.rcm.PointFrame') ~= ...
        "robot_base"
    error('scopeguide:config:InvalidRcmPointFrame', ...
        'Only robot_base is supported for cfg.rcm.PointFrame.');
end
validRcmPointSources = ["unset", "manual_base_coordinate", ...
    "multiaxis_calibration"];
rcmPointSource = scalarString(cfg.rcm.PointSource, ...
    'cfg.rcm.PointSource');
if ~any(rcmPointSource == validRcmPointSources)
    error('scopeguide:config:InvalidRcmPointSource', ...
        'cfg.rcm.PointSource is not supported.');
end
optionalScalarString(cfg.rcm.PointSourceDescription, ...
    'cfg.rcm.PointSourceDescription');
optionalScalarString(cfg.rcm.FixtureIdentifier, ...
    'cfg.rcm.FixtureIdentifier');
optionalScalarString(cfg.rcm.PointRecordedAtLocal, ...
    'cfg.rcm.PointRecordedAtLocal');
positiveScalar(cfg.rcm.SoftRadiusM, 'cfg.rcm.SoftRadiusM');
positiveScalar(cfg.rcm.HardRadiusM, 'cfg.rcm.HardRadiusM');
if cfg.rcm.SoftRadiusM >= cfg.rcm.HardRadiusM
    error('scopeguide:config:InvalidRcmBounds', ...
        'SoftRadiusM must be strictly smaller than HardRadiusM.');
end
logicalScalar(cfg.rcm.CalibrationValid, 'cfg.rcm.CalibrationValid');
logicalScalar(cfg.rcm.BoundsValidated, 'cfg.rcm.BoundsValidated');
if all(isfinite(cfg.rcm.PointBaseM)) && rcmPointSource == "unset"
    error('scopeguide:config:RcmPointSourceRequired', ...
        'A finite RCM point requires a declared source.');
end
if cfg.rcm.CalibrationValid && ...
        (~all(isfinite(cfg.rcm.PointBaseM)) || rcmPointSource == "unset")
    error('scopeguide:config:InvalidRcmCalibrationState', ...
        'CalibrationValid requires a finite RCM point and source.');
end
if cfg.rcm.BoundsValidated && ~cfg.rcm.CalibrationValid
    error('scopeguide:config:InvalidRcmBoundsState', ...
        'BoundsValidated requires CalibrationValid=true.');
end

logicalScalar(cfg.safety.ThresholdsValidated, ...
    'cfg.safety.ThresholdsValidated');
logicalScalar(cfg.safety.JointLimitsValidated, ...
    'cfg.safety.JointLimitsValidated');
validateSafetyThresholds(cfg.safety);
validateStage08Config(cfg.stage08, cfg.kinematics, cfg.runtime);

if any(mode == ["offline_replay", "live_dry_run"])
    if cfg.robot.EnableMotion || ~cfg.robot.DryRun
        error('scopeguide:config:UnsafeDryRunConfiguration', ...
            'Offline and live dry-run modes require EnableMotion=false and DryRun=true.');
    end
end

if cfg.robot.EnableMotion
    if cfg.robot.DryRun || ~any(mode == ["fixture_motion", "phantom_motion"])
        error('scopeguide:config:UnsafeMotionConfiguration', ...
            ['EnableMotion=true requires DryRun=false and a fixture_motion ' ...
            'or phantom_motion mode.']);
    end
elseif ~cfg.robot.DryRun
    error('scopeguide:config:InconsistentMotionFlags', ...
        'DryRun=false is invalid while EnableMotion=false.');
end
end

function validateStage08Config(stage08, kinematics, runtime)
required = {'DofMode', 'ProfileApplied', 'AllowedDofModes', 'SpeedScale', ...
    'PivotAdmittanceSpeedScale', 'PivotTargetSpeedMultiplier', ...
    'PivotMaximumSpeedMultiplier', ...
    'PivotSpeedRetuneApplied', 'PivotSpeedRetuneRevision', ...
    'ProgrammaticRobotEnable', 'EnablePayloadKg', ...
    'SpeedFactorPercent', 'PostEnablePauseSec', ...
    'SpeedFactorFeedbackTolerance', 'DisableRobotOnExit', ...
    'KeyboardInputMode', 'InputHeartbeatTimeoutSec', ...
    'JointLimitMarginRad', 'MaximumServoTargetStepRad', ...
    'MaximumServoSendSec', 'MaximumTargetFeedbackErrorRad', ...
    'MaximumConsecutiveTrackingErrors', 'StopVelocityThresholdRadSec', ...
    'MaximumStopLatencySec', 'RequiredRobotModes', ...
    'RequireIndependentEmergencyStop', 'EmergencyStopAttested', ...
    'EmergencyStopAttestationSource', 'RequireSecondObserver', ...
    'RequireFixtureAndClearanceConfirmation', ...
    'SetupConfirmationPhrase', 'SafetyThresholdConfirmationPhrase', ...
    'AllowServoTimingBootstrap', 'BootstrapDofMode', ...
    'CompletedDofModes'};
for index = 1:numel(required)
    if ~isstruct(stage08) || ~isfield(stage08, required{index})
        error('scopeguide:config:MissingStage08Field', ...
            'cfg.stage08.%s is required.', required{index});
    end
end
allowed = string(stage08.AllowedDofModes);
if isempty(allowed) || any(ismissing(allowed)) || ...
        any(strlength(allowed) == 0) || numel(unique(allowed)) ~= numel(allowed)
    error('scopeguide:config:InvalidStage08DofModes', ...
        'cfg.stage08.AllowedDofModes must contain unique nonempty modes.');
end
logicalScalar(stage08.ProfileApplied, 'cfg.stage08.ProfileApplied');
logicalScalar(stage08.PivotSpeedRetuneApplied, ...
    'cfg.stage08.PivotSpeedRetuneApplied');
positiveScalar(stage08.PivotAdmittanceSpeedScale, ...
    'cfg.stage08.PivotAdmittanceSpeedScale');
positiveScalar(stage08.PivotTargetSpeedMultiplier, ...
    'cfg.stage08.PivotTargetSpeedMultiplier');
positiveScalar(stage08.PivotMaximumSpeedMultiplier, ...
    'cfg.stage08.PivotMaximumSpeedMultiplier');
if stage08.PivotAdmittanceSpeedScale > 4.5 || ...
        stage08.PivotTargetSpeedMultiplier > 3 || ...
        stage08.PivotMaximumSpeedMultiplier > 3
    error('scopeguide:config:UnsafeStage08PivotSpeedMultiplier', ...
        'Stage 8 pivot speed multipliers must not exceed 3.');
end
if ~isnumeric(stage08.PivotSpeedRetuneRevision) || ...
        ~isscalar(stage08.PivotSpeedRetuneRevision) || ...
        ~isfinite(stage08.PivotSpeedRetuneRevision) || ...
        stage08.PivotSpeedRetuneRevision ~= 3
    error('scopeguide:config:InvalidStage08PivotRetuneRevision', ...
        'cfg.stage08.PivotSpeedRetuneRevision must equal 3.');
end
if logical(stage08.ProfileApplied) ~= ...
        logical(stage08.PivotSpeedRetuneApplied)
    error('scopeguide:config:InconsistentStage08PivotRetuneState', ...
        ['ProfileApplied and PivotSpeedRetuneApplied must have the same ' ...
         'state.']);
end
logicalScalar(stage08.ProgrammaticRobotEnable, ...
    'cfg.stage08.ProgrammaticRobotEnable');
logicalScalar(stage08.DisableRobotOnExit, ...
    'cfg.stage08.DisableRobotOnExit');
if stage08.ProgrammaticRobotEnable && ~stage08.DisableRobotOnExit
    error('scopeguide:config:Stage08DisableOnExitRequired', ...
        ['ProgrammaticRobotEnable=true requires ' ...
         'DisableRobotOnExit=true.']);
end
nonnegativeScalar(stage08.EnablePayloadKg, ...
    'cfg.stage08.EnablePayloadKg');
if stage08.EnablePayloadKg > 5
    error('scopeguide:config:InvalidStage08EnablePayload', ...
        'cfg.stage08.EnablePayloadKg must lie in [0,5] kg.');
end
if ~isnumeric(stage08.SpeedFactorPercent) || ...
        ~isscalar(stage08.SpeedFactorPercent) || ...
        ~isfinite(stage08.SpeedFactorPercent) || ...
        stage08.SpeedFactorPercent ~= fix(stage08.SpeedFactorPercent) || ...
        stage08.SpeedFactorPercent < 1 || ...
        stage08.SpeedFactorPercent > 30
    error('scopeguide:config:UnsafeStage08SpeedFactor', ...
        ['cfg.stage08.SpeedFactorPercent must be an integer in ' ...
         '[1,30].']);
end
positiveScalar(stage08.PostEnablePauseSec, ...
    'cfg.stage08.PostEnablePauseSec');
if stage08.PostEnablePauseSec < 2 || stage08.PostEnablePauseSec > 10
    error('scopeguide:config:InvalidStage08PostEnablePause', ...
        'cfg.stage08.PostEnablePauseSec must lie in [2,10] seconds.');
end
positiveScalar(stage08.SpeedFactorFeedbackTolerance, ...
    'cfg.stage08.SpeedFactorFeedbackTolerance');
if stage08.SpeedFactorFeedbackTolerance > 1
    error('scopeguide:config:InvalidStage08SpeedFactorTolerance', ...
        ['cfg.stage08.SpeedFactorFeedbackTolerance must not exceed ' ...
         '1 percentage point.']);
end
completed = string(stage08.CompletedDofModes);
if any(ismissing(completed)) || any(strlength(completed) == 0) || ...
        any(~ismember(completed, allowed)) || ...
        numel(unique(completed)) ~= numel(completed)
    error('scopeguide:config:InvalidStage08CompletedModes', ...
        'CompletedDofModes must be unique members of AllowedDofModes.');
end
mode = scalarString(stage08.DofMode, 'cfg.stage08.DofMode');
bootstrapMode = scalarString(stage08.BootstrapDofMode, ...
    'cfg.stage08.BootstrapDofMode');
if ~any(mode == allowed) || ~any(bootstrapMode == allowed)
    error('scopeguide:config:InvalidStage08DofMode', ...
        'Stage 8 DOF modes must belong to AllowedDofModes.');
end
if scalarString(stage08.KeyboardInputMode, ...
        'cfg.stage08.KeyboardInputMode') ~= "space_on_escape_off"
    error('scopeguide:config:InvalidStage08KeyboardMode', ...
        'Stage 8 requires the Space-ON / Esc-OFF latch.');
end
if ~isnumeric(stage08.SpeedScale) || ~isscalar(stage08.SpeedScale) || ...
        ~isfinite(stage08.SpeedScale) || stage08.SpeedScale <= 0 || ...
        stage08.SpeedScale > 4.5
    error('scopeguide:config:UnsafeStage08SpeedScale', ...
        'cfg.stage08.SpeedScale must lie in (0, 4.5].');
end
positiveScalar(stage08.InputHeartbeatTimeoutSec, ...
    'cfg.stage08.InputHeartbeatTimeoutSec');
positiveScalar(stage08.JointLimitMarginRad, ...
    'cfg.stage08.JointLimitMarginRad');
positiveScalar(stage08.MaximumServoTargetStepRad, ...
    'cfg.stage08.MaximumServoTargetStepRad');
positiveScalar(stage08.MaximumServoSendSec, ...
    'cfg.stage08.MaximumServoSendSec');
positiveScalar(stage08.MaximumTargetFeedbackErrorRad, ...
    'cfg.stage08.MaximumTargetFeedbackErrorRad');
positiveScalar(stage08.StopVelocityThresholdRadSec, ...
    'cfg.stage08.StopVelocityThresholdRadSec');
positiveScalar(stage08.MaximumStopLatencySec, ...
    'cfg.stage08.MaximumStopLatencySec');
if stage08.MaximumServoSendSec > runtime.MaximumDtSec
    error('scopeguide:config:Stage08ServoSendBudgetTooLarge', ...
        'MaximumServoSendSec must not exceed runtime.MaximumDtSec.');
end
if ~isnumeric(stage08.MaximumConsecutiveTrackingErrors) || ...
        ~isscalar(stage08.MaximumConsecutiveTrackingErrors) || ...
        ~isfinite(stage08.MaximumConsecutiveTrackingErrors) || ...
        stage08.MaximumConsecutiveTrackingErrors < 1 || ...
        stage08.MaximumConsecutiveTrackingErrors ~= ...
        fix(stage08.MaximumConsecutiveTrackingErrors)
    error('scopeguide:config:InvalidStage08TrackingCount', ...
        'MaximumConsecutiveTrackingErrors must be a positive integer.');
end
requiredRobotModes = string(stage08.RequiredRobotModes);
if isempty(requiredRobotModes) || any(ismissing(requiredRobotModes)) || ...
        any(strlength(requiredRobotModes) == 0)
    error('scopeguide:config:InvalidStage08RobotModes', ...
        'RequiredRobotModes must contain at least one robot mode.');
end
logicalScalar(stage08.RequireIndependentEmergencyStop, ...
    'cfg.stage08.RequireIndependentEmergencyStop');
logicalScalar(stage08.EmergencyStopAttested, ...
    'cfg.stage08.EmergencyStopAttested');
logicalScalar(stage08.RequireSecondObserver, ...
    'cfg.stage08.RequireSecondObserver');
logicalScalar(stage08.RequireFixtureAndClearanceConfirmation, ...
    'cfg.stage08.RequireFixtureAndClearanceConfirmation');
logicalScalar(stage08.AllowServoTimingBootstrap, ...
    'cfg.stage08.AllowServoTimingBootstrap');
optionalScalarString(stage08.EmergencyStopAttestationSource, ...
    'cfg.stage08.EmergencyStopAttestationSource');
scalarString(stage08.SetupConfirmationPhrase, ...
    'cfg.stage08.SetupConfirmationPhrase');
scalarString(stage08.SafetyThresholdConfirmationPhrase, ...
    'cfg.stage08.SafetyThresholdConfirmationPhrase');
jointLower = double(kinematics.JointLowerLimitRad(:));
jointUpper = double(kinematics.JointUpperLimitRad(:));
if any(jointLower + stage08.JointLimitMarginRad >= ...
        jointUpper - stage08.JointLimitMarginRad)
    error('scopeguide:config:Stage08JointMarginTooLarge', ...
        'Stage 8 joint margin leaves an empty admissible interval.');
end
end

function validateAdmittanceConfig(admittance, control)
if ~isstruct(admittance) || ~isfield(admittance, 'Pivot') || ...
        ~isfield(admittance, 'Insertion') || ...
        ~isfield(admittance, 'VelocityZeroTolerance')
    error('scopeguide:config:MissingAdmittanceField', ...
        ['cfg.admittance must contain Pivot, Insertion and ' ...
        'VelocityZeroTolerance.']);
end
pivotNames = {'DesignForceN', 'NominalLeverArmM', ...
    'TargetSteadySpeedRadSec', 'TimeConstantSec', ...
    'MaximumAccelerationRadSec2', 'MaximumTipSpeedMSec'};
for index = 1:numel(pivotNames)
    name = pivotNames{index};
    if ~isfield(admittance.Pivot, name)
        error('scopeguide:config:MissingAdmittanceField', ...
            'cfg.admittance.Pivot.%s is required.', name);
    end
    positiveScalar(admittance.Pivot.(name), ...
        ['cfg.admittance.Pivot.', name]);
end
insertionNames = {'DesignForceN', 'TargetSteadySpeedMSec', ...
    'TimeConstantSec', 'MaximumAccelerationMSec2'};
for index = 1:numel(insertionNames)
    name = insertionNames{index};
    if ~isfield(admittance.Insertion, name)
        error('scopeguide:config:MissingAdmittanceField', ...
            'cfg.admittance.Insertion.%s is required.', name);
    end
    positiveScalar(admittance.Insertion.(name), ...
        ['cfg.admittance.Insertion.', name]);
end
positiveFiniteVector(admittance.VelocityZeroTolerance, 3, ...
    'cfg.admittance.VelocityZeroTolerance');
if admittance.Pivot.TargetSteadySpeedRadSec > ...
        control.PivotMaxRadSec
    error('scopeguide:config:AdmittanceTargetExceedsLimit', ...
        ['Pivot TargetSteadySpeedRadSec must not exceed the configured ' ...
        'pivot speed limit.']);
end
if admittance.Insertion.TargetSteadySpeedMSec > ...
        control.InsertionMaxMSec
    error('scopeguide:config:AdmittanceTargetExceedsLimit', ...
        ['Insertion TargetSteadySpeedMSec must not exceed the configured ' ...
        'insertion speed limit.']);
end
end

function validateQpConfig(qp, runtime, kinematics)
if ~isstruct(qp)
    error('scopeguide:config:MissingQpField', ...
        'cfg.qp must be a scalar structure.');
end
requiredPositive = {'TaskCharacteristicLengthM', ...
    'TaskTrackingWeight', 'JointVelocityRegularization', ...
    'SoftRcmWeight', 'HybridRcmWeightMinimum', ...
    'HybridRcmWeightMaximum', 'RcmRecoveryGainMinimumSecInv', ...
    'RcmRecoveryGainMaximumSecInv', 'JointCenteringGainSecInv', ...
    'JointCenteringMaximumRadSec', 'JointPositionMarginRad', ...
    'SingularityStopSigma', 'SingularityFullSpeedSigma', ...
    'ConstraintTolerance', 'OptimalityTolerance', ...
    'MaximumSolveTimeSec'};
requiredIntegers = {'HardConstraintPolygonSides', ...
    'RelativePivotPolygonSides', 'MaximumIterations', ...
    'MaximumConsecutiveFailures'};
required = [{'Solver'}, requiredPositive, requiredIntegers];
for index = 1:numel(required)
    if ~isfield(qp, required{index})
        error('scopeguide:config:MissingQpField', ...
            'cfg.qp.%s is required.', required{index});
    end
end
if scalarString(qp.Solver, 'cfg.qp.Solver') ~= "quadprog"
    error('scopeguide:config:InvalidQpSolver', ...
        'Stage 6 requires cfg.qp.Solver="quadprog".');
end
for index = 1:numel(requiredPositive)
    name = requiredPositive{index};
    positiveScalar(qp.(name), ['cfg.qp.', name]);
end
for index = 1:numel(requiredIntegers)
    name = requiredIntegers{index};
    value = qp.(name);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || ...
            value ~= fix(value) || value < 1
        error('scopeguide:config:InvalidQpInteger', ...
            'cfg.qp.%s must be a positive integer.', name);
    end
end
if qp.HardConstraintPolygonSides < 8 || ...
        qp.RelativePivotPolygonSides < 8
    error('scopeguide:config:QpPolygonTooCoarse', ...
        'RCM and relative-pivot polygons require at least 8 sides.');
end
if qp.HybridRcmWeightMaximum < qp.HybridRcmWeightMinimum || ...
        qp.RcmRecoveryGainMaximumSecInv < ...
        qp.RcmRecoveryGainMinimumSecInv
    error('scopeguide:config:InvalidQpGainOrder', ...
        'QP maximum weights/gains must not be smaller than minimums.');
end
if qp.SingularityFullSpeedSigma <= qp.SingularityStopSigma
    error('scopeguide:config:InvalidQpSingularityThresholds', ...
        'SingularityFullSpeedSigma must exceed SingularityStopSigma.');
end
if qp.JointPositionMarginRad >= kinematics.MaximumAbsJointAngleRad
    error('scopeguide:config:InvalidQpJointMargin', ...
        'JointPositionMarginRad must be smaller than the joint range.');
end
if qp.MaximumSolveTimeSec > runtime.NominalDtSec
    error('scopeguide:config:InvalidQpSolveBudget', ...
        'MaximumSolveTimeSec must not exceed NominalDtSec.');
end
end

function validateBaselineConfig(baseline)
required = {'StartupZeroEnabled', 'StartupDurationSec', ...
    'StartupMaximumForceNormN', 'StartupMaximumMomentNormNm', ...
    'TrackingComponentMask', 'MinimumEligibleDurationSec', ...
    'UpdateTimeConstantSec', ...
    'MaximumForceUpdateRateNSec', 'MaximumMomentUpdateRateNmSec', ...
    'MaximumForceOffsetN', 'MaximumMomentOffsetNm', ...
    'EligibilityForceNormN', 'EligibilityMomentNormNm'};
for index = 1:numel(required)
    if ~isstruct(baseline) || ~isfield(baseline, required{index})
        error('scopeguide:config:MissingBaselineField', ...
            'cfg.force.Baseline.%s is required.', required{index});
    end
end
logicalScalar(baseline.StartupZeroEnabled, ...
    'cfg.force.Baseline.StartupZeroEnabled');
positiveScalar(baseline.StartupDurationSec, ...
    'cfg.force.Baseline.StartupDurationSec');
positiveScalar(baseline.StartupMaximumForceNormN, ...
    'cfg.force.Baseline.StartupMaximumForceNormN');
positiveScalar(baseline.StartupMaximumMomentNormNm, ...
    'cfg.force.Baseline.StartupMaximumMomentNormNm');
if ~islogical(baseline.TrackingComponentMask) || ...
        numel(baseline.TrackingComponentMask) ~= 6
    error('scopeguide:config:InvalidBaselineTrackingMask', ...
        'cfg.force.Baseline.TrackingComponentMask must be a 6-element logical vector.');
end
nonnegativeScalar(baseline.MinimumEligibleDurationSec, ...
    'cfg.force.Baseline.MinimumEligibleDurationSec');
positiveScalar(baseline.UpdateTimeConstantSec, ...
    'cfg.force.Baseline.UpdateTimeConstantSec');
positiveScalar(baseline.MaximumForceUpdateRateNSec, ...
    'cfg.force.Baseline.MaximumForceUpdateRateNSec');
positiveScalar(baseline.MaximumMomentUpdateRateNmSec, ...
    'cfg.force.Baseline.MaximumMomentUpdateRateNmSec');
positiveScalar(baseline.MaximumForceOffsetN, ...
    'cfg.force.Baseline.MaximumForceOffsetN');
positiveScalar(baseline.MaximumMomentOffsetNm, ...
    'cfg.force.Baseline.MaximumMomentOffsetNm');
positiveScalar(baseline.EligibilityForceNormN, ...
    'cfg.force.Baseline.EligibilityForceNormN');
positiveScalar(baseline.EligibilityMomentNormNm, ...
    'cfg.force.Baseline.EligibilityMomentNormNm');
end

function validateSafetyThresholds(safety)
names = {'RawForceStopN', 'RawMomentStopNm', ...
    'FastForceWarningN', 'FastForceStopN', ...
    'FastMomentWarningNm', 'FastMomentStopNm', ...
    'FastForceRateStopNSec'};
for index = 1:numel(names)
    if ~isfield(safety, names{index})
        error('scopeguide:config:MissingSafetyThreshold', ...
            'cfg.safety.%s is required.', names{index});
    end
    positiveScalar(safety.(names{index}), ['cfg.safety.', names{index}]);
end
if safety.FastForceWarningN >= safety.FastForceStopN || ...
        safety.FastMomentWarningNm >= safety.FastMomentStopNm
    error('scopeguide:config:InvalidSafetyThresholdOrder', ...
        'Fast warning thresholds must be smaller than stop thresholds.');
end
end

function requireField(value, fieldName, parentName)
if ~isstruct(value) || ~isfield(value, fieldName)
    error('scopeguide:config:MissingField', ...
        '%s.%s is required.', parentName, fieldName);
end
end

function value = scalarString(inputValue, name)
value = string(inputValue);
if ~isscalar(value) || ismissing(value) || strlength(value) == 0
    error('scopeguide:config:InvalidString', ...
        '%s must be a nonempty scalar string.', name);
end
end

function value = optionalScalarString(inputValue, name)
value = string(inputValue);
if ~isscalar(value) || ismissing(value)
    error('scopeguide:config:InvalidString', ...
        '%s must be a scalar string.', name);
end
end

function logicalScalar(value, name)
if ~islogical(value) || ~isscalar(value)
    error('scopeguide:config:InvalidLogical', ...
        '%s must be a logical scalar.', name);
end
end

function positiveScalar(value, name)
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value <= 0
    error('scopeguide:config:InvalidPositiveScalar', ...
        '%s must be a finite positive scalar.', name);
end
end

function nonnegativeScalar(value, name)
if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value) || value < 0
    error('scopeguide:config:InvalidNonnegativeScalar', ...
        '%s must be a finite nonnegative scalar.', name);
end
end

function value = positiveFiniteVector(inputValue, count, name)
value = finiteVector(inputValue, count, name);
if any(value <= 0)
    error('scopeguide:config:InvalidPositiveVector', ...
        '%s must contain only positive values.', name);
end
end

function vector = finiteVector(value, count, name)
if ~isnumeric(value) || numel(value) ~= count || any(~isfinite(value(:)))
    error('scopeguide:config:InvalidVector', ...
        '%s must contain %d finite numeric values.', name, count);
end
vector = value(:);
end

function validateTransform(transform, name)
if ~isnumeric(transform) || ~isequal(size(transform), [4, 4]) || ...
        any(~isfinite(transform(:)))
    error('scopeguide:config:InvalidTransform', ...
        '%s must be a finite 4-by-4 numeric matrix.', name);
end
if norm(transform(4, :) - [0, 0, 0, 1], inf) > 1e-12
    error('scopeguide:config:InvalidTransform', ...
        '%s must have homogeneous bottom row [0 0 0 1].', name);
end
rotation = transform(1:3, 1:3);
if norm(rotation' * rotation - eye(3), 'fro') > 1e-10 || ...
        abs(det(rotation) - 1) > 1e-10
    error('scopeguide:config:InvalidTransform', ...
        '%s rotation must be right-handed and orthonormal.', name);
end
end

function validateRcmPoint(value)
if ~isnumeric(value) || numel(value) ~= 3
    error('scopeguide:config:InvalidRcmPoint', ...
        'rcm.PointBaseM must contain three numeric values.');
end
value = value(:);
if ~(all(isfinite(value)) || all(isnan(value)))
    error('scopeguide:config:InvalidRcmPoint', ...
        'rcm.PointBaseM must be fully finite or fully unknown (NaN).');
end
end
